IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_HESAP_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_HESAP_SATIRI
CREATE TABLE #TOHOM_ISKELE_HESAP_SATIRI (
	SATIR_NO	INT NULL,
	GRUP_NO TINYINT NULL,
	HESAP_ID	INT NOT NULL,
	PROJEMIZ_ID	INT NULL,
	AKTIVITE_ID	INT NULL,
	MASRAF_MERKEZI_ID	INT NULL,
	BUTCE_KALEMI_ID	INT NULL,
	BUTCE_BOLUMU_ID	INT NULL,
	CARI_KESINTI_KALEMI_ID	INT NULL,
	ACIKLAMA	NVARCHAR(200)	COLLATE database_default NULL,
	VALOR		DATETIME NULL,
	TIP		TINYINT NULL,
	MIKTAR		FLOAT NULL,
	PARA_MIKTARI	FLOAT NULL,
	PARA_KURU	FLOAT NULL,
	IKINCI_PARA_MIKTARI	FLOAT NULL,
	IKINCI_PARA_KURU	FLOAT NULL,
	PARTI_YAMASI_ID INT NULL,
	URUN_MIKTARI	FLOAT NULL,
	BIRIM_ID	INT NULL,
	SILINDI BIT NULL-- Toplu odemenin tek hesap hareketinde olusmasý icin yapildi
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_MUH_FIS_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_MUH_FIS_SATIRI
CREATE TABLE #TOHOM_ISKELE_MUH_FIS_SATIRI (
	SATIR_NO	INT NULL,
	MUH_HESAP_ID	INT NULL,
	ACIKLAMA	NVARCHAR(200)	COLLATE database_default NULL,
	ACIKLAMA2	NVARCHAR(200)	COLLATE database_default NULL,
	TIP		TINYINT NULL,
	MEBLAG		FLOAT NULL,
	DOVIZ_MIKTARI	FLOAT NULL,
	PARA_ID		INT NULL,
	URUN_MIKTARI	FLOAT NULL,
	BIRIM_ID	INT NULL,
	YEVMIYE_SATIR_NO INT NULL,
	FON_MIKTARI INT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_MUH_ENVANTER_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_MUH_ENVANTER_SATIRI
CREATE TABLE #TOHOM_ISKELE_MUH_ENVANTER_SATIRI (
	SATIR_NO	INT NULL,
	MUH_HESAP_ID	INT NULL,
	ACIKLAMA	NVARCHAR(200)	COLLATE database_default NULL,
	PARA_MIKTARI	FLOAT NULL,
	PARA_ID		INT NULL,
	KUR	FLOAT NULL,
	TUTAR		FLOAT NULL,
	PARTI_YAMASI_ID INT NULL,
	VARLIK_KODU	NCHAR(50)	COLLATE database_default NULL,
	VARLIK_ADI	NVARCHAR(200)	COLLATE database_default NULL,
	VARLIK_MIKTARI	FLOAT NULL,
	BIRIM_ID	INT NULL,
	KAYIT_NO INT NULL,
)
go
IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CEKI_PAKETI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CEKI_PAKETI
CREATE TABLE #TOHOM_ISKELE_CEKI_PAKETI (
	CEKI_PAKETI_ID INT NULL,
	SIRA_NO INT NULL,
	AMBALAJ_ID INT NULL,
	AMBALAJ_NO NCHAR(50)	COLLATE database_default NULL,
	ACIKLAMA NVARCHAR(200)	COLLATE database_default NULL,
	AGIRLIK FLOAT NULL,
	AGIRLIK_BIRIMI_ID INT NULL,
	HACIM FLOAT NULL,
	HACIM_BIRIMI_ID INT NULL,
	MASRAF_PAYLASIM_YONTEMI TINYINT NULL,
	TEDARIKCI_ID INT NULL,
)

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CEKI_URUNU') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CEKI_URUNU
CREATE TABLE #TOHOM_ISKELE_CEKI_URUNU (
	CEKI_PAKETI_ID INT NULL,
	CEKI_PAKETI_SIRA_NO INT NULL,
	CEKI_URUNU_ID INT NULL,
	SIRA_NO INT NULL,
	FATURA_SATIRI_ID INT NULL,
	MIKTAR FLOAT NULL,
	AGIRLIK FLOAT NULL,
	AGIRLIK_BIRIMI_ID INT NULL,
	HACIM FLOAT NULL,
	HACIM_BIRIMI_ID INT NULL,
	ACIKLAMA NVARCHAR(200)	COLLATE database_default NULL,
)

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_GUMRUK_CEKIMI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_GUMRUK_CEKIMI_SATIRI
CREATE TABLE #TOHOM_ISKELE_GUMRUK_CEKIMI_SATIRI (
	GUMRUK_CEKIMI_SATIRI_ID INT NULL,
	SATIR_NO INT NULL,
	CEKI_PAKETI_ID INT NULL,
	CEKI_URUNU_ID INT NULL,
	MIKTAR FLOAT NULL,
)


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_IS_FISI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_IS_FISI_SATIRI
CREATE TABLE #TOHOM_ISKELE_IS_FISI_SATIRI (
	IS_FISI_SATIRI_ID		INT NULL,
	SATIR_NO			INT NULL,
	LOT_ID				INT NULL,
	MALZEME_ID			INT NULL,
	MIKTAR				FLOAT NULL,
	BIRIM_ID			INT NULL,
	PERSONEL_ID			INT NULL,
	SURE				INT NULL,
	SURE_BIRIMI			TINYINT NULL,
	MALIYET_KALEMI_ID		INT NULL,
	BIRIM_MALIYET			FLOAT NULL,
	PARA_ID				INT NULL,
	KUR				FLOAT NULL,
	TUTAR				FLOAT NULL,
	FATURA_SATIRI_ID INT NULL,
	HARCAMA_SATIRI_ID INT NULL,
	MALZEME_KULLANIM_SATIRI_ID INT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_FL_SURUM_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_FL_SURUM_SATIRI
CREATE TABLE #TOHOM_ISKELE_FL_SURUM_SATIRI (
	FL_SURUM_ID INT NULL,
	SATIR_NO INT NULL,
	URUN_ID INT NULL,
	BIRIM_ID INT NULL,
	ILK_DEGER FLOAT NULL,
	SON_DEGER FLOAT NULL,
	ACIKLAMA NVARCHAR(200)	COLLATE database_default NULL,
	REVIZE_EDEN_ID INT NULL,
	REVIZE_TARIHI DATETIME NULL,
	FIYAT_KAYNAGI_ID INT NULL,
	KULLANILAN_KOLON_NO INT NULL,
	KOLON_NO INT NULL,
	FIYAT FLOAT NULL,
	PARA_ID INT NULL,
	KDV_DAHIL BIT NULL,
	FIYAT_DEGISTIRILDI BIT NULL,
	YUZDE FLOAT NULL,
	ISKONTO_ORANI FLOAT NULL,
	VADE INT NULL,
	VADE_BIRIMI TINYINT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_DURAN_VARLIK_FIS_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_DURAN_VARLIK_FIS_SATIRI
CREATE TABLE #TOHOM_ISKELE_DURAN_VARLIK_FIS_SATIRI (
	DURAN_VARLIK_FIS_SATIRI_ID		INT NULL,
	SATIR_NO			INT NULL,
	PROJEMIZ_ID			INT NULL,
	MASRAF_MERKEZI_ID		INT NULL,
	GIDER_YERI_ID		INT NULL,
	DURAN_VARLIK_ID			INT NULL,
	YONTEM				TINYINT NULL,
	AMORTISMAN_ORANI		FLOAT NULL,
	AMORTISMAN_PAYI			FLOAT NULL,
	AMORTISMAN_AYIRMA_ATLANDI BIT NULL,
	YENIDEN_DEGERLEME_ORANI	FLOAT NULL,
	DURAN_VARLIK_DEGERLEME	FLOAT NULL,
	BIRIKMIS_AMORTISMAN_DEGERLEME FLOAT NULL,
	AYRILMIS_AMORTISMAN_DEGERLEME FLOAT NULL,
	ACIKLAMA			NVARCHAR(200)	COLLATE database_default NULL,
	MIKTAR	FLOAT NULL,
	BIRIM_ID INT NULL,
	ONCEKI_ID INT NULL,
	AMORTISMAN_DEGISTI BIT NULL,
	VARLIK_DEGERLEME_DEGISTI BIT NULL
)
go


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CEKI_LISTESI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CEKI_LISTESI_SATIRI
CREATE TABLE #TOHOM_ISKELE_CEKI_LISTESI_SATIRI (
	CEKI_LISTESI_SATIRI_ID	INT NULL,
	SATIR_NO			INT NULL,
	SEVIYE 				INT NULL,
	AMBALAJ_ID 			INT NULL,
	AMBALAJ_NO			NCHAR(50)	COLLATE database_default NULL,
	AMBALAJ_MIKTARI		FLOAT NULL,
	ACIKLAMA 			NCHAR(50)	COLLATE database_default NULL,
	SIPARIS_SATIRI_ID	INT NULL,
	DEPOLANAN_URUN_ID INT NULL,
	MIKTAR				FLOAT NULL,
	BIRIM_ID			INT NULL,
	BARKOD              NCHAR(50) NULL,
	NET_AGIRLIK			FLOAT NULL,
	NET_AGIRLIK_BIRIMI_ID	INT NULL,
	NET_AGIRLIK_HESAPLANSIN BIT NULL,
	BRUT_AGIRLIK		FLOAT NULL,
	BRUT_AGIRLIK_BIRIMI_ID	INT NULL,
	BRUT_AGIRLIK_HESAPLANSIN BIT NULL,
	HACIM 				FLOAT NULL,
	HACIM_BIRIMI_ID  	INT NULL,
	HACIM_HESAPLANSIN	BIT NULL,
	BIRIM_DARA		FLOAT NULL,
	DARA_BIRIMI_ID  	INT NULL,
	BIRIM_FIYATI		FLOAT NULL,
	PARA_ID  		INT NULL,
	PAKETLEYEN_ID 		INT NULL,
	MUHATAP_ID 		INT NULL,
	DEPO_FISI_SATIRI_ID 		INT NULL,
	URETIM_EMRI_ID 		INT NULL,
	HAKKINDA		NVARCHAR(512)	COLLATE database_default NULL,
	KAP_KULLANIM_SEKLI TINYINT NULL,
	AMBALAJ_RECETESI_ID INT NULL,
	TASERON_IHR_SIPARIS_SATIRI_ID INT NULL,
	SIPARIS_BIRIM_FIYATI FLOAT,
	SIPARIS_TUTAR FLOAT,
	SIPARIS_ISKONTO_ORANI FLOAT,
	SIPARIS_ISKONTO FLOAT,
	URUN_TARIFI NVARCHAR(1024)		COLLATE database_default,
	FIRE_ORANI FLOAT NULL,
	FIRE FLOAT NULL,
	ONCEKI_ID INT NULL,
	BARKOD_ID INT NULL,
	RUSUM_ORANI FLOAT NULL,
	URUN_IZLEME_ID INT NULL,
	FATURA_NO NVARCHAR(50)	COLLATE database_default,
	CIKMA_MIKTARI FLOAT,
	FATURA_KONUSU_ID INT,
	PROJEMIZ_ID INT,
	URETICI_ID INT,
	GGN_ID INT
)	
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_CARI_DEKONT_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_CARI_DEKONT_SATIRI

CREATE TABLE #TOHOM_CARI_DEKONT_SATIRI (
	SATIR_NO		INT NULL,
	PARTI_YAMASI_ID INT,
	PARTI_YAMASI_HESAP_TURU TINYINT,
	PROJEMIZ_ID INT,
	ACIKLAMA NVARCHAR(200) COLLATE database_default,
	TIP TINYINT,
	MIKTAR FLOAT,
	PARA_ID INT,
	KUR FLOAT,
	TUTAR FLOAT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_BANKA_DEKONT_MASRAFI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_BANKA_DEKONT_MASRAFI
CREATE TABLE #TOHOM_ISKELE_BANKA_DEKONT_MASRAFI (
	SATIR_NO INT NULL,
	HARCAMA_KALEMI_ID INT NULL,
	AKTIVITE_ID	INT NULL,
	BUTCE_KALEMI_ID	INT NULL,
	BUTCE_BOLUMU_ID	INT NULL,
	MIKTAR	FLOAT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CEKI_LISTESI_SEVKIYATI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CEKI_LISTESI_SEVKIYATI
CREATE TABLE #TOHOM_ISKELE_CEKI_LISTESI_SEVKIYATI (
	SATIR_NO INT NULL,
	SEFER_ID INT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SEYAHAT_TALEP_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SEYAHAT_TALEP_SATIRI
CREATE TABLE #TOHOM_ISKELE_SEYAHAT_TALEP_SATIRI (
       IZIN_TALEBI_ID       INT NULL,
       SATIR_NO             INT NULL,
       YOLCU_ID             INT NULL,
       NEREDEN_ID           INT NULL,
       NEREYE_ID            INT NULL,
       ULKE_ID              INT NULL,
       TAHMINI_VARIS_TARIHI DATETIME NULL,
       TAHMINI_KALIS_SURESI INT NULL,
       TAHMINI_KALIS_SURE_BIRIMI INT NULL,
       TALEP_EDEN_PERSONEL_ID INT NULL,
       PROJEMIZ_ID          INT NULL,
       TASERON_ID           INT NULL,
       MASRAFI_KARSILAYAN   TINYINT NULL,
       GOREV_ID             INT NULL,
       SIPARIS_ID           INT NULL,
       YOLCU_DURUMU         INT NULL,
       MASRF_KARSILAYAN_PERSONEL_ID INT NULL,
	   YAPILACAK_IS			NVARCHAR(200)	COLLATE database_default,
	   KALACAK_YER			NVARCHAR(200)	COLLATE database_default,
       ACIKLAMA				NVARCHAR(200)	COLLATE database_default,
       YOLCU_ADI			NVARCHAR(50)	COLLATE database_default,
       VIZE_TARIHI			DATETIME NULL,
       AKTARMA_ID			INT NULL
)   
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_DOVIZ_FISI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_DOVIZ_FISI_SATIRI
CREATE TABLE #TOHOM_ISKELE_DOVIZ_FISI_SATIRI (
	TIP TINYINT NULL,
	SATIR_NO	INT NULL,
	MIKTAR		FLOAT NULL,
	PARA_ID	INT NULL,
	KUR	FLOAT NULL,
	TUTAR		FLOAT NULL,
	TUTAR_HESAPLANMASIN		BIT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_VIRMAN_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_VIRMAN_SATIRI
CREATE TABLE #TOHOM_ISKELE_VIRMAN_SATIRI (
       VIRMAN_SATIRI_ID     INT,
       SATIR_NO             INT,
       GRUP_NO TINYINT,
       MUHATAP_CINSI        TINYINT,
       MUHATAP_ID           INT,
       MUHATAP_HESAP_TURU   TINYINT,
       PROJEMIZ_ID          INT,
       AKTIVITE_ID          INT,
       MASRAF_MERKEZI_ID    INT,
       GIDER_YERI_ID    INT,
       SOZLESME_ID          INT,
       BUTCE_KALEMI_ID			INT,
       BUTCE_BOLUMU_ID			INT,
       CARI_KESINTI_KALEMI_ID INT,
       KESINTI_HARCAMA_ID INT,
       ACIKLAMA             NVARCHAR(200)	COLLATE database_default,
       VADE                 DATETIME,
       TIP                  TINYINT,
       MIKTAR               FLOAT,
       PARA_ID              INT,
       KUR                  FLOAT,
       TUTAR                FLOAT,
       SUBE_MUHATAP_CINSI   TINYINT,
       SUBE_MUHATAP_ID           INT,
       SUBE_MUHATAP_HESAP_TURU   TINYINT,
       GUID				UNIQUEIDENTIFIER,
       ONCEKI_ID           INT,
       SOZLESME_SORUMLUSU TINYINT,
       SOZLESME_PARA_ID           INT,
       HAKEDIS_ID INT,
       PARA_TALEBI_ID INT,
       BORDRO_YILI INT,
       BORDRO_AYI INT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SIGORTA_POLICE_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SIGORTA_POLICE_SATIRI
CREATE TABLE #TOHOM_ISKELE_SIGORTA_POLICE_SATIRI (
       SATIR_NO             INT,
       PROJEMIZ_ID          INT,
       MASRAF_MERKEZI_ID    INT,
       SIGORTALANAN_ID      INT,
       TASERON_ID		    INT,
       TASERON_SIGORTALANAN NVARCHAR(200)	COLLATE database_default,
       SIGORTA_BEDELI       FLOAT,
       ACIKLAMA             NVARCHAR(200)	COLLATE database_default,
       GIDER_YERI_ID    INT
)
go


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_AVANS_TALEBI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_AVANS_TALEBI
CREATE TABLE #TOHOM_ISKELE_AVANS_TALEBI (
       SIPARIS_ID            INT,
       PROJEMIZ_ID          INT,
       TUTAR				FLOAT,
       PARA_ID				INT,
       KUR					FLOAT,
	   VADE					DATETIME,
	   ORAN					FLOAT,
	   MIKTAR				FLOAT,
	   ODEME_SEKLI			TINYINT,
	   YENI_KAYIT		    BIT,
	   KDVSIZ_TUTAR			FLOAT, -- SOHOMC_SIPARIS_AVANS_TALEBI'de kullaniliyor
	   ODEME_PLANI_ID		INT -- SOHOMC_SIPARIS_AVANS_TALEBI_ESKI'de kullaniliyor
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_OLCU_BIRIMI_DEGISTIR') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_OLCU_BIRIMI_DEGISTIR
CREATE TABLE #TOHOM_ISKELE_OLCU_BIRIMI_DEGISTIR (
	KAYNAK_OLCU_SISTEMI_ID	INT,
	HEDEF_OLCU_SISTEMI_ID	INT,
	SATIR_NO 				INT,
	KAYNAK_AD		 		NVARCHAR(100)	COLLATE database_default NULL,
	KAYNAK_KISALTMA 		NVARCHAR(20)	COLLATE database_default NULL,
	HEDEF_AD		 		NVARCHAR(100)	COLLATE database_default NULL,
	HEDEF_KISALTMA 			NVARCHAR(20)	COLLATE database_default NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SEYAHAT_HARCAMASI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SEYAHAT_HARCAMASI
CREATE TABLE #TOHOM_ISKELE_SEYAHAT_HARCAMASI (
	HARCAMA_SATIRI_NO	INT,
	SEYAHAT_FORM_SATIRI_ID INT,
	SEYAHAT_MASRAF_TURU_ID	INT,
	TUTAR				FLOAT,
	SEFER_ID INT,
	SOZLESME_ID INT,
	MASRAFI_KARSILAYAN INT,
	MASRAFI_KARSILAYAN_ID INT,
	ACIKLAMA NVARCHAR(200)	COLLATE database_default
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ZIMMET_FORMU_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ZIMMET_FORMU_SATIRI
CREATE TABLE #TOHOM_ISKELE_ZIMMET_FORMU_SATIRI (
	ZIMMET_FORMU_SATIRI_ID	INT NULL,
	ZIMMET_FORMU_ID	INT,
	SATIR_NO INT,
	DEPO_FISI_SATIRI_ID	INT,
	DURAN_VARLIK_ID	INT,
	MIKTAR		FLOAT,
	ACIKLAMA	NVARCHAR(512)	COLLATE database_default NULL,
	ONCEKI_ID INT,
	DEVREDEN_ID INT
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_IZIN_TALEBI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_IZIN_TALEBI_SATIRI
CREATE TABLE #TOHOM_ISKELE_IZIN_TALEBI_SATIRI (
   IZIN_TALEBI_ID       INT,
   IZIN_TALEBI_SATIRI_ID INT,
   SATIR_NO             INT,
   IZIN_TIPI_ID			INT,
   MAZERET_NEDENI_ID    INT,
   KALAN_IZIN_HAKKI     INT,
   AVANS_IZIN_HAKKI     INT,
   BASLANGIC_ZAMANI     DATETIME,
   BITIS_ZAMANI         DATETIME,
   SURE                 INT,
   ACIKLAMA				NVARCHAR(200)	COLLATE database_default,
   ONAYLANDI			BIT NULL,
   MASRAFI_KARSILAYAN   TINYINT NULL,
   TALEP_EDILEN_SURE    INT,
   HAFTA_TATILI_SURESI	INT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_TAKVIM_GUNU') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_TAKVIM_GUNU
CREATE TABLE #TOHOM_ISKELE_TAKVIM_GUNU (
	HAFTANIN_GUNU		INT NULL,
	OZEL_GUNUN_TARIHI	DATETIME NULL,
	FIILI_MESAI			BIT NULL,
	MESAI_TIPI			TINYINT NOT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_TAKVIM_GUNU_DILIMI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_TAKVIM_GUNU_DILIMI
CREATE TABLE #TOHOM_ISKELE_TAKVIM_GUNU_DILIMI (
	HAFTANIN_GUNU		INT NULL,
	OZEL_GUNUN_TARIHI	DATETIME NULL,
	DILIM_NO			INT NULL,
	MESAI_BASLANGICI	DATETIME NULL,
	MESAI_BITISI		DATETIME NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_MALI_ENVANTER') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_MALI_ENVANTER
CREATE TABLE #TOHOM_ISKELE_MALI_ENVANTER (
	DEPOLANAN_URUN_ID INT,
	BAKIYE FLOAT NULL,
	FIYAT FLOAT NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_TASERON_MLZ_MUTABAKATI') AND xtype = 'U')
	DROP TABLE #TOHOM_TASERON_MLZ_MUTABAKATI
CREATE TABLE #TOHOM_TASERON_MLZ_MUTABAKATI (
	SERVIS_ISLEMI_ID INT,
	TASERON_MLZ_MUTABAKATI_ID INT,
	SATIR_NO INT,
	DEPOLANAN_URUN_ID INT,
	AKTIVITE_ID INT,
	METRAJ FLOAT NULL,
	METRAJ_BIRIM_ID INT,
	SARFIYAT_CARPANI FLOAT NULL,
	FIRE_ORANI FLOAT NULL,
	KULLANILAN_MIKTAR FLOAT NULL,
	TASERON_STOK_MIKTARI FLOAT NULL,
	FATURA_EDILECEK_MIKTAR FLOAT NULL,
	BIRIM_FIYAT FLOAT NULL,
	PARA_ID INT,
	FATURA_EDILECEK_TUTAR FLOAT NULL,
	FATURA_EDILSIN BIT NULL,
	ONCEKI_METRAJ FLOAT NULL,
	ONCEKI_KULLANILAN_MIKTAR FLOAT NULL,
	ONCEKI_FATURALANAN_MIKTAR FLOAT NULL,
	KULLANILAN_MIKTAR_DEGISTI BIT NULL,
	FATURA_MIKTARI_DEGISTI BIT NULL,
	ZAM_ORANI FLOAT NULL,
	ZAMLI_FIYAT FLOAT NULL,
	FIYAT_HESAPLAMA_SEKLI INT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_TMLZ_MUTABAKAT_DETAY') AND xtype = 'U')
	DROP TABLE #TOHOM_TMLZ_MUTABAKAT_DETAY
CREATE TABLE #TOHOM_TMLZ_MUTABAKAT_DETAY (
	TASERON_MLZ_MUTABAKATI_ID INT,
	SATIR_NO INT,
	DEPO_FISI_SATIRI_ID INT,
	MALZEME_KULLANIM_MIKTARI FLOAT NULL,
	FATURA_MIKTARI FLOAT NULL,
	KULLANIM_MIKTARI_DEGISTI BIT NULL,
	FATURA_MIKTARI_DEGISTI BIT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_OLCU_BIRIMI') AND xtype = 'U')
	DROP TABLE #TOHOM_OLCU_BIRIMI
CREATE TABLE #TOHOM_OLCU_BIRIMI (
       OLCU_BIRIMI_ID       INT,
       SIRA_NO              INT NOT NULL,
       AD                   NVARCHAR(200)		COLLATE database_default NOT NULL,
       KISALTMA             NVARCHAR(10)		COLLATE database_default NOT NULL,
       KATSAYI              FLOAT NOT NULL,
       ZAMAN_KARSILIGI      TINYINT,
       UNECE				NVARCHAR(10)		COLLATE database_default,
       GUID					UNIQUEIDENTIFIER,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ARIZA_TALEP_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ARIZA_TALEP_SATIRI
CREATE TABLE #TOHOM_ISKELE_ARIZA_TALEP_SATIRI (
	SATIR_NO		INT,
	ARIZA_TALEP_SATIRI_ID		INT,
	ARIZA_TALEBI_ID		INT,
	PARTI_YAMASI_ID		INT,
	ARAC_SAATI			FLOAT,
	ARAC_SAATI_BIRIM_ID	INT,
	PROJEMIZ_ID	INT,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ARIZA_TALEP_ISTASYON') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ARIZA_TALEP_ISTASYON
CREATE TABLE #TOHOM_ISKELE_ARIZA_TALEP_ISTASYON (
	SATIR_NO		INT,
	ISTASYON_ID		INT,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ARIZA_YORUM') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ARIZA_YORUM
CREATE TABLE #TOHOM_ISKELE_ARIZA_YORUM (
	SATIR_NO		INT,
	PERSONEL_ID		INT,
	PERSONEL_TEXT	NVARCHAR(50)	COLLATE database_default,
	GOREV_ID		INT,
	YORUM			NVARCHAR(200)	COLLATE database_default
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_BILGI_KUPU_MIZAN') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_BILGI_KUPU_MIZAN
CREATE TABLE #TOHOM_ISKELE_BILGI_KUPU_MIZAN (
	AY_NO			INT NOT NULL,
	AY				NVARCHAR(10)	COLLATE database_default NOT NULL,
	HESAP			NVARCHAR(512)	COLLATE database_default NOT NULL,
	HESAP_FILTRE_1	NVARCHAR(200)	COLLATE database_default NULL,
	HESAP_FILTRE_2	NVARCHAR(200)	COLLATE database_default NULL,
	HESAP_FILTRE_3	NVARCHAR(200)	COLLATE database_default NULL,
	HESAP_FILTRE_4	NVARCHAR(200)	COLLATE database_default NULL,
	HESAP_FILTRE_5	NVARCHAR(200)	COLLATE database_default NULL,
	PROJE			NVARCHAR(200)	COLLATE database_default NULL,
	CARI_KESINTI	NVARCHAR(512)	COLLATE database_default NULL,
	MASRAF_MERKEZI	NVARCHAR(512)	COLLATE database_default NULL,

	ANA_PARA_BORC_TOPLAMI		FLOAT	NULL,
	ANA_PARA_ALACAK_TOPLAMI		FLOAT	NULL,
	ANA_PARA_BAKIYE_TOPLAMI		FLOAT	NULL,
	ANA_PARA_KURUS_SAYISI		INT		NULL,

	IKINCI_PARA_BORC_TOPLAMI	FLOAT	NULL,
	IKINCI_PARA_ALACAK_TOPLAMI	FLOAT	NULL,
	IKINCI_PARA_BAKIYE_TOPLAMI	FLOAT	NULL,
	IKINCI_PARA_KURUS_SAYISI	INT		NULL,

	HEDEF_PARA_BORC_TOPLAMI		FLOAT	NULL,
	HEDEF_PARA_ALACAK_TOPLAMI	FLOAT	NULL,
	HEDEF_PARA_BAKIYE_TOPLAMI	FLOAT	NULL,
	HEDEF_PARA_KURUS_SAYISI		INT		NULL,

	ORJINAL_PARA_BORC_TOPLAMI	FLOAT	NULL,
	ORJINAL_PARA_ALACAK_TOPLAMI	FLOAT	NULL,
	ORJINAL_PARA_BAKIYE_TOPLAMI	FLOAT	NULL,
	ORJINAL_PARA_KURUS_SAYISI	INT		NULL,
	ORJINAL_PARA_ID				INT		NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SUBE_KESINTI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SUBE_KESINTI_SATIRI
CREATE TABLE #TOHOM_ISKELE_SUBE_KESINTI_SATIRI (
	SUBE_KESINTI_SATIRI_ID	INT	NULL,
	SATIR_NO				INT	NULL,
	PROJEMIZ_ID				INT	NULL,
	SEFER_DAGILIMI_ID		INT	NULL,
	CEKI_LISTESI_ID			INT	NULL,
	HARCAMA_KALEMI_ID		INT	NULL,
	ALT_GIDER_ID			INT	NULL,
	ACIKLAMA				NVARCHAR(200)	COLLATE database_default NULL,
	MIKTAR					FLOAT	NULL,
	PARA_ID					INT	NULL,
	KUR						FLOAT	NULL,
	TUTAR					FLOAT	NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_HKS_KULLANILAN_KUNYE') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_HKS_KULLANILAN_KUNYE
CREATE TABLE #TOHOM_ISKELE_HKS_KULLANILAN_KUNYE (
	DEPO_FISI_SATIRI_ID	INT	NULL,
	FATURA_SATIRI_ID	INT	NULL,
	SATIR_NO	INT	NOT NULL,
	HKS_STOK_KUNYE_ID	INT	NULL,
	HKS_SATIS_KUNYE_ID	INT	NULL,
	MIKTAR				FLOAT	NOT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_HKS_MAGAZA') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_HKS_MAGAZA
CREATE TABLE #TOHOM_ISKELE_HKS_MAGAZA (
	SIRA_NO			INT NULL,
	ADRES_TUR_ADI	NVARCHAR(200) NULL,
	AD				NVARCHAR(200) NULL,
	HKS_ID			INT NULL,
	HAL_ID			INT NULL,
	ISYERI_TURU		INT NULL,
	IL_ID			INT NULL,
	ILCE_ID			INT NULL,
	BELDE_ID		INT NULL,
	ADRES			NVARCHAR(200) NULL,
	HKS_YER_ID		INT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_KANTAR_HAREKET_DETAYI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_KANTAR_HAREKET_DETAYI
CREATE TABLE #TOHOM_ISKELE_KANTAR_HAREKET_DETAYI (
		SATIR_NO             INT,
		FIS_NO               NCHAR(50) COLLATE database_default,
		MUHATAP_ID           INT,
		SIPARIS_SATIRI_ID    INT,
		DEPOLANAN_URUN_ID    INT,
		KALITE_ID            INT,
		BOY_ID               INT,
		PALET_ID             INT,
		PALET_RECETESI_ID    INT,
		PALET_DARASI         FLOAT,
		PALET_SAYISI         FLOAT,
		PALET_KAPASITESI     FLOAT,
		KAP_ID               INT,
		KAP_KULLANIM_SEKLI   TINYINT,
		KAP_RECETESI_ID      INT,
		KAP_DARASI           FLOAT,
		KAP_SAYISI           FLOAT,
		ARA_TARTI            FLOAT,
		KAP_KAPASITESI       FLOAT,
		URUN_MIKTARI         FLOAT,
		URUN_BIRIMI_ID       INT,
		BRUT_AGIRLIK         FLOAT,
		URETICI_ID			 INT,
		CIKMA_MIKTARI		 FLOAT,
		FIRE_ORANI			 FLOAT,
		BIRIM_FIYATI	     FLOAT,
		PARA_ID      	     INT
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_FON_KAPAMA') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_FON_KAPAMA
CREATE TABLE #TOHOM_ISKELE_FON_KAPAMA (
	DEKONT_ID	INT	NULL,
	MIKTAR		FLOAT	NULL
)
GO


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SINIRLAMA') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SINIRLAMA
CREATE TABLE #TOHOM_ISKELE_SINIRLAMA (
	ROL_SINIRLAMASI_ID INT,
	SINIRLAMA_TURU TINYINT,
	MESAJ NVARCHAR(512)			COLLATE database_default,
	ONAYLAYAN_ID INT,
	ACIKLAMA NVARCHAR(1024)	COLLATE database_default,
	ONAY_NUMERIK_DEGERI FLOAT,
	ONAY_XID INT,
	VEKIL_ID INT,
	ONERILEN_FIRMA_ID INT,
	SINIRLAMA_GUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	GOREV_ONAY_OGESI_ID INT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CARI_HAREKET_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CARI_HAREKET_SATIRI
CREATE TABLE #TOHOM_ISKELE_CARI_HAREKET_SATIRI (
       CARI_HAREKET_SATIRI_ID INT,
       CARI_ID              INT,
       CARI_HESAP_TURU      TINYINT,
       PROJEMIZ_ID          INT,
       VADE                 DATETIME,
       TIP                  TINYINT,
       ORAN                 FLOAT,
       MIKTAR               FLOAT,
       PARA_ID              INT,
       KUR                  FLOAT,
       TUTAR                FLOAT,
       ODEME_SEKLI          TINYINT,
       ACIKLAMA             NVARCHAR(50) COLLATE database_default,
	   ODEME_EMRI_CARI_HAREKET_SATIRI_ID INT,
	   KESINTI_ID			INT,
       HESAP_ID             INT,
       ODENDI				BIT,
       PARITE               FLOAT,
       KARSILIK             FLOAT,
       KARSILIK_PARA_ID     INT,
       KDV_SATIRI BIT,
	   ENTEGRASYON_KODU NCHAR(50) COLLATE database_default,
       VADE_SEKLI          TINYINT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_CARI_KAPAMA') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_CARI_KAPAMA

CREATE TABLE #TOHOM_ISKELE_CARI_KAPAMA (
       CARI_HAREKET_SATIRI_ID      INT,
       MIKTAR               FLOAT,
       ODEME_EMRI_ID        INT,
	   KREDI_KARSILIGI FLOAT,
	   KAPATAN_SATIR_ID INT
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ENVANTER_SATIRI_YATAY') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ENVANTER_SATIRI_YATAY

CREATE TABLE #TOHOM_ISKELE_ENVANTER_SATIRI_YATAY (
	FIS_SATIR_NO INT,
	SATIR_NO INT,
	MIKTAR FLOAT,
	SAYIM_MIKTARI FLOAT,
	ENVANTER0_ID INT,
	ENVANTER1_ID INT,
	ENVANTER2_ID INT,
	ENVANTER3_ID INT,
	ENVANTER4_ID INT,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_OZELLIK_DEGERI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_OZELLIK_DEGERI

CREATE TABLE #TOHOM_ISKELE_OZELLIK_DEGERI (
	SAHIP			INT,
	SERI_NO			NCHAR(40) COLLATE database_default,
	OZELLIK_ID		INT,
	TUR			TINYINT,
	STRING_DEGER		NVARCHAR(MAX) COLLATE database_default,
	TARIH_DEGERI		DATETIME,
	NUMERIK_DEGER		FLOAT,
	XID			INT,
	FIYAT                   FLOAT,
	FIYAT_PARA_ID   	INT,
	ACIKLAMA 		NVARCHAR(MAX) COLLATE database_default,
	NOT_ID  		INT,
	MIKTAR FLOAT,
	SIRA_NO INT,
	ADLANDIRMADA_KULLAN BIT,
	AYRAC TINYINT,
	OZELLIK_GUID UNIQUEIDENTIFIER,
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_ODEME_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_ODEME_SATIRI

CREATE TABLE #TOHOM_ISKELE_ODEME_SATIRI (
	POS_CIHAZI_ID INT,
	KK_SOZLESME_ID INT,
	KREDI_KARTI_ID INT,
	SATIR_NO	INT,
	MIKTAR		FLOAT,
	PARA_ID		INT,
	KUR		FLOAT,
	TAKSIT_SAYISI INT,
	BANKA_HESABI_ID INT
)
go


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_OB_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_OB_SATIRI


CREATE TABLE #TOHOM_ISKELE_OB_SATIRI (
	ODEME_ARACI_TURU	TINYINT,
	SATIR_NO		INT,
	ODEME_ARACI_ID		INT,
	ODEME_ARACI_SAHIBI	BIT,
	PORTFOY_NO		NVARCHAR(50) COLLATE database_default,
	ODEME_ARACI_NO		NVARCHAR(40) COLLATE database_default,
	DUZENLEYEN_ID		INT,
	DUZENLEME_TARIHI	DATETIME,
	MUHATAP_ID		INT,
	VADE_TARIHI		DATETIME,
	MIKTAR			FLOAT,
	PARA_ID			INT,
	KUR			FLOAT,
	VALOR_ZAMANI		INT,
	VALOR_ZAMAN_BIRIMI	TINYINT,
	VADE_FARKI_ORANI	FLOAT,
	VADE_FARKI_ZAMAN_BIRIMI	TINYINT,
	BASKASINA_AIT		BIT,
	BORCLUSU_ID		INT,
	CIROLAR			NVARCHAR(200) COLLATE database_default,
	MASRAF_BORCLUDAN	BIT,
	MASRAF			FLOAT,
	HAKKINDA		NVARCHAR(200) COLLATE database_default,
	CEK_BANKA_ID		INT,
	CEK_SUBE_ADI		NVARCHAR(40) COLLATE database_default,
	CEK_BANKA_HESAP_NO	NVARCHAR(40) COLLATE database_default,
	CEK_KESIDE_YERI		NVARCHAR(40) COLLATE database_default,
	CEK_MASRAF_BORCLUDAN	BIT,
	SENET_SEHIR_ID		INT,
	SENET_PUL_TUTARI	FLOAT,
	SENET_EKSIK_PUL_BEDELI	FLOAT,
	SENET_KEFILLER		NVARCHAR(200) COLLATE database_default,
	ALINAN_TEMINAT_MEKTUBU_BANKA_ID INT,
	ALINAN_TEMINAT_MEKTUBU_SUBE_ADI NVARCHAR(40) COLLATE database_default,
	ALINAN_TEMINAT_MEKTUBU_KONU_ID INT,
	PARCALI_TAHSILAT_MIKTARI FLOAT,
	TEMINAT_MEKTUBU_TEMINAT_TURU      TINYINT ,
	TEMINAT_MEKTUBU_KOMISYON_SEKLI      TINYINT ,
	TEMINAT_MEKTUBU_KOMISYON_ORANI      FLOAT,
	TEMINAT_MEKTUBU_KOMISYON_ORANI_BIRIMI TINYINT,
	TEMINAT_MEKTUBU_KOMISYON_MIKTARI    FLOAT,
	TEMINAT_MEKTUBU_KOMISYON_MIKTARI_PARA_ID INT,
	TEMINAT_MEKTUBU_KOMISYON_DONEMI     INT,
	TEMINAT_MEKTUBU_KOMISYON_DONEMI_BIRIMI TINYINT,
	VERILEN_TEMINAT_MEKTUBU_ORTAKLIK_PAYI        FLOAT,
)
go


IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_DOKUMAN_SAHIBI_TURU') AND xtype = 'U')
	DROP TABLE #TOHOM_DOKUMAN_SAHIBI_TURU
CREATE TABLE #TOHOM_DOKUMAN_SAHIBI_TURU (
	KULLANICI_ID	INT,
	SAHIP_TURU		TINYINT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_YETKILI_DOKUMAN_SAHIBI') AND xtype = 'U')
	DROP TABLE #TOHOM_YETKILI_DOKUMAN_SAHIBI
CREATE TABLE #TOHOM_YETKILI_DOKUMAN_SAHIBI (
	KULLANICI_ID			INT,
	YENI					INT NULL,
	SAHIP_TURU				TINYINT,
	SAHIP_ID				INT,
	SAHIP_PARTI_TURU		TINYINT,
	SAHIP_PARTI_YAMALARI	INT,
	INTEGRA_SAHIP_KODU		NVARCHAR(200)	COLLATE database_default NULL,
	INTEGRA_SAHIP_ADI		NVARCHAR(200)	COLLATE database_default NULL,
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_YETKILI_DOKUMAN') AND xtype = 'U')
	DROP TABLE #TOHOM_YETKILI_DOKUMAN
CREATE TABLE #TOHOM_YETKILI_DOKUMAN (
	KULLANICI_ID			INT,
	YENI					INT NULL,
	SAHIP_TURU				TINYINT,
	SAHIP_ID				INT,
	SAHIP_PARTI_TURU		TINYINT,
	INTEGRA_SAHIP_KODU		NVARCHAR(200)	COLLATE database_default NULL,
	DOKUMAN_ID				INT,
	AD						NVARCHAR(200)	COLLATE database_default NULL,
	DOKUMAN_TIPI			NVARCHAR(10)	COLLATE database_default NULL,
	EKLEME_ZAMANI			DATETIME,
	DIS_KAYNAKLI			BIT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_AD') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_AD
CREATE TABLE #TOHOM_ISKELE_AD (
       DIL                  TINYINT NOT NULL,
       AD                   NVARCHAR(200)	COLLATE database_default NOT NULL
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_PARTI_YAMASI_HESABI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_PARTI_YAMASI_HESABI
CREATE TABLE #TOHOM_ISKELE_PARTI_YAMASI_HESABI (
       TUR                  TINYINT NOT NULL,
       HESAP_ID             INT NOT NULL,
       ACILDI               BIT,
       ALT_HESAP_ACMA_SEKLI TINYINT NOT NULL
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_MASRAF_FISI_SATIRI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_MASRAF_FISI_SATIRI
CREATE TABLE #TOHOM_ISKELE_MASRAF_FISI_SATIRI (
		MASRAF_FISI_SATIRI_ID INT,
		SATIR_NO             INT,
		CARI_KART_ID         INT,
		UNVAN	             NVARCHAR(200)	COLLATE database_default,
		BELGESIZ			 BIT,
		FIS_NO               nchar(50) COLLATE database_default,
		FIS_TARIHI           DATETIME,
		ACIKLAMA             NVARCHAR(200)	COLLATE database_default,
		HARCAMA_KALEMI_ID    INT,
		MIKTAR               FLOAT,
		PARA_ID              INT,
		KAPANDI				 BIT,
)
GO

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_BUTCE_DEGERI') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_BUTCE_DEGERI 

CREATE TABLE #TOHOM_ISKELE_BUTCE_DEGERI (
       TIP                  TINYINT,
       OZELLIK_ID           INT,
       AY                   INT,
       DEGER                FLOAT,
       DEGISTIRILDI         BIT,
       DETAY                BIT,
       SIRA_NO              INT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_BUTCE_URUNU') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_BUTCE_URUNU 

CREATE TABLE #TOHOM_ISKELE_BUTCE_URUNU (
       SATIR_NO              INT,
       URUN_YAMASI_ID       INT,
       HARCAMA_KALEMI_ID       INT,
       ACIKLAMA	NVARCHAR(200)	COLLATE database_default,
       BIRIM_ID             INT,
       PARA_ID              INT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_BUTCE_URUNU_DEGER') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_BUTCE_URUNU_DEGER 

CREATE TABLE #TOHOM_ISKELE_BUTCE_URUNU_DEGER (
       SATIR_NO  INT,
       AY       INT,
       MIKTAR   FLOAT,
       FIYAT    FLOAT
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ISKELE_SGK_RAPORU') AND xtype = 'U')
	DROP TABLE #TOHOM_ISKELE_SGK_RAPORU
CREATE TABLE #TOHOM_ISKELE_SGK_RAPORU (
       SGK_RAPOR_ID INT,
       TAKIP_NO NVARCHAR(50)	COLLATE database_default,
       TC_KIMLIK_NO NVARCHAR(50)	COLLATE database_default,
       BASLAMA_TARIHI DATETIME,
       BITIS_TARIHI DATETIME
)
go

IF EXISTS (SELECT * FROM tempdb.dbo.sysobjects WHERE id = OBJECT_ID('tempdb..#TOHOM_ONAY_NOTU_DETAYI') AND xtype = 'U')
	DROP TABLE #TOHOM_ONAY_NOTU_DETAYI
CREATE TABLE #TOHOM_ONAY_NOTU_DETAYI (
       VADE DATETIME,
	   MIKTAR FLOAT,
	   PARA_ID INT,
	   ODEME_SEKLI TINYINT
)
go
