USE FD_hom
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SOHOM_SIPARIS_KAYDET
	@SIPARIS_ID KAYIT_ID OUTPUT,
	@PARTI_YAMASI_ID KAYIT_ID,
	@TIP TUR,
	@EVRAK_KONUSU_ID KAYIT_ID,
	@SIPARIS_NO KOD OUTPUT,
	@TARIH TARIH,
	@OPSIYON_TARIHI TARIH,
	@KUR_TARIHI TARIH,
	@PARA_ID KAYIT_ID = 1,
	@KUR MIKTAR = 1.0,
	@KARSI_REF_NO KOD = NULL,
	@ONCELIK_ID MADDE,
	@TOPLAM_TUTAR MIKTAR = 0.0,
	@ISKONTO_ORANI ORAN = 0.0,
	@ISKONTO_HESAPLANMASIN BOOL = 0,
	@ISKONTO MIKTAR = 0.0,
	@ISKONTO_TOPLAMI MIKTAR = 0.0,
	@KDV_ORANI ORAN = 0.0,
	@HESAPLANAN_ORTALAMA_VADE SURE = 0,
	@ACIKLAMA ACIKLAMA200,
	@ILGI_CINSI TUR = NULL,
	@ILGILI_ID KAYIT_ID = NULL,
	@IPTAL_FISI BOOL = 0,
	@ODEME_PLANI_ID KAYIT_ID = NULL,
	@ORTALAMA_VADE SURE = NULL,
	@ORTALAMA_VADE_BIRIMI TUR = NULL,
	@VALOR_ZAMANI SURE = NULL,
	@VALOR_ZAMAN_BIRIMI TUR = NULL,
	@VADE_FARKI_ORANI ORAN = NULL,
	@VADE_FARKI_ZAMAN_BIRIMI TUR = NULL,
	@MUHATAP_BANKA_ID KAYIT_ID = NULL,
	@FIRMAMIZ_BANKA_HESAP_ID KAYIT_ID = NULL,
	@ODEME_YETKILISI_ID KAYIT_ID = NULL,
	@ODEME_ADRESI ACIKLAMA200 = NULL,
	@TICARET_SEKLI TUR = NULL,
	@TESLIMAT_YETKILISI_ID KAYIT_ID,
	@TESLIMAT_ADRESI ACIKLAMA200,
	@TESLIMAT_BICIMI TUR,
	@TESLIMAT_SEKLI_ID MADDE,
	@TESLIMAT_SURESI SURE,
	@TESLIMAT_SURESI_BIRIMI TUR,
	@YOLA_CIKIS_TARIHI TARIH,
	@YUKLEME_YERI ACIKLAMA200,
	@YUKLEME_TARIHI TARIH,
	@VARACAGI_YER ACIKLAMA200,
	@TAHMINI_VARIS_TARIHI TARIH,
	@NAKLIYATCI_ID KAYIT_ID,
	@NAKLIYATCI_ACENTA_ID KAYIT_ID,
	@NAKLIYAT_SIGORTASINI_USTLENEN TUR,
	@NAKLIYAT_SIGORTACISI_ID KAYIT_ID,
	@NAKLIYAT_SIGORTACISI_ACENTA_ID KAYIT_ID,
	@GUMRUKCU_ID KAYIT_ID,
	@ULASIM_SEKLI_ID MADDE,
	@ULASIM_DETAYI ACIKLAMA200,
	@KOMISYONCU_ID KAYIT_ID = NULL,
	@KOMISYON_ORANI ORAN = 0.0,
	@FATURA_YETKILISI_ID KAYIT_ID = NULL,
	@FATURA_ADRESI ACIKLAMA200 = NULL,
	@HAKKINDA ACIKLAMA3072,
	@NOT1 ACIKLAMA1024,
	@NOT2 ACIKLAMA1024,
	@NOT3 ACIKLAMA1024,
	@ONCEKI_ID KAYIT_ID = NULL,
	@KEFIL_ID KAYIT_ID = NULL,
	@IHZARAT_ODEME_ORANI ORAN = NULL,
	@SOZLESME_KONUSU ACIKLAMA512 = NULL,
	@SOZLESME_BASLANGIC_TARIHI TARIH = NULL,
	@SOZLESME_BITIS_TARIHI TARIH = NULL,
	@SAHIP_TURU TUR = NULL,
	@SAHIP_ID KAYIT_ID = NULL,
	@KDV_TEVKIFAT_TANIMI_ID KAYIT_ID = NULL,
	@NIHAI_MUSTERI_ID KAYIT_ID = NULL,
	@SIPARIS_TURU TUR = NULL,
	@SOZLESME_TURU TUR = NULL,
	@ALIM_YERI TUR = NULL,
	@SECILEN_FIRMA_ID KAYIT_ID = NULL,
	@KDV_DURUMU TUR = 0,
	@GARANTI_SURESI SURE = NULL,
	@GARANTI_SURESI_BIRIMI TUR = NULL,
	@GARANTI_VEREN_ID KAYIT_ID = NULL,
	@KUR_TIPI TUR = 1,
	@FIYATLANDIRMA_BICIMI TUR = NULL,
	@NAKLIYE_UCRETI_DAHIL BOOL = NULL,
	@NAKLIYE_UCRETI MIKTAR = NULL,
	@NAKLIYE_UCRETI_PARA_ID KAYIT_ID = NULL,
	@BARTER_FATURALAMA_SEKLI TUR = NULL,
	@GECICI_IHRACAT_ICINDIR BOOL = NULL,
	@SATINALAN_SUBE_ID KAYIT_ID = NULL,
	@SATINALMA_BEDELI MIKTAR = NULL,
	@UYGULAYAN_SUBE_ID KAYIT_ID = NULL,
	@UYGULAMA_BEDELI MIKTAR = NULL,
	@TAKSIT_VADE_FARKI_ORANI ORAN = NULL,
	@TAKSIT_VADE_FARKI_ZAMAN_BIRIMI TUR = NULL,
	@TAKSITLENDIRME_DEGISTIRILDI BOOL = NULL,
	@TAKSITLENDIRME_SEKLI TUR = 0,					/*105*/
	@PESINAT MIKTAR = 0.0,
	@SGK_ISCILIK_ORANI ORAN = NULL,
	@ZEYILNAME_KONUSU ACIKLAMA512 = NULL,
	@RUSUM_TOPLAMI MIKTAR = 0.0,
	@RUSUM_KDV_MATRAHINA_DAHIL BOOL = 0,
	@ODEME_PLANI_HAKKINDA ACIKLAMA512 = NULL,
	@KAYNAK_SIPARIS_ID KAYIT_ID = NULL,
	@ISCILIK_AZAMI_KAR_ORANI ORAN = 0.0,
	@FATURA_UYGULANAN_PARA_SECIMI TUR = 0,
	@DOKUMANI_VAR BOOL = 0,
	@SOZLESME_DOKUMANI_VAR BOOL = 0,
	@KAR_ORANI ORAN = 0.0,
	@KAYNAK_ID KAYIT_ID = NULL,
	@DURUM_ID MADDE = NULL,
	@TESLIMAT_ADRESI_ID KAYIT_ID = NULL,
	@ALT_HESAP_ID KAYIT_ID = NULL,
	@FIYAT_FARKI_INDEKS_ID MADDE = NULL,
	@FIYAT_FARKI_ORANI ORAN = NULL,
	@IDARE_KESINTI_ORANI ORAN = NULL,
	@METRAJ_GIRIS_SEKLI TUR = 0,
	@KULLANICI_ID KAYIT_ID,
	@GUID UNIQUEIDENTIFIER,
	@DENETIM_ISLEMI  TUR, /* 0  : denetle ve sorun yoksa oanylı kaydet -- 1 : Onaya sunmadan onaysız kaydet   2 : Sorunsuz ise onaylı kaydet varsa onaya sun ve onaysız kaydet*/
	@ONAY_DURUMU TUR = 0  OUT /* 0 : Onaya sunulmuş talep yok 1 : Onaya sunulmuş talep var 2 : Onaylanmış talep var*/
WITH ENCRYPTION AS
BEGIN
	DECLARE @HATA_NO INT
	DECLARE @HATA_MESAJI ACIKLAMA200
	DECLARE @DONUS_KODU INT
	DECLARE @ONAYLANDI BOOL
	DECLARE @KURUS_SAYISI TAMSAYI
	DECLARE @YENI_KAYIT BOOL
	DECLARE @ZAMAN ZAMAN
	SET @ZAMAN = GETDATE()
	IF (@SIPARIS_ID IS NULL) SET @YENI_KAYIT = 1
	ELSE SET @YENI_KAYIT = 0
	DECLARE @PROJEMIZ_ID KAYIT_ID
	SET @PROJEMIZ_ID = NULL
	SET ROWCOUNT 1
	SELECT @PROJEMIZ_ID = PROJEMIZ_ID FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI WHERE GUID = @GUID AND PROJEMIZ_ID IS NOT NULL ORDER BY SATIR_NO
	IF @@ROWCOUNT = 0
	BEGIN
		IF @ILGI_CINSI = 7 SET @PROJEMIZ_ID = @ILGILI_ID
	END
	SET ROWCOUNT 0
	DECLARE @SIPARIS_ALT_TUR TUR
	DECLARE @SENARYO TUR
	DECLARE @HESAP_HAREKETI_URET BOOL
	DECLARE @CARI_HAREKET_URET BOOL
	SET @HESAP_HAREKETI_URET = 0
	SET @CARI_HAREKET_URET = 0
	SELECT @SIPARIS_ALT_TUR = ALT_TUR, @SENARYO = EKRAN_GIRIS_SENARYOSU,
			@HESAP_HAREKETI_URET = CASE WHEN @TIP = 0 THEN CASE WHEN ALT_TUR = 5 THEN 1 WHEN ALT_TUR = 8 THEN ISNULL(HESAP_HAREKETI_URET,0) ELSE 0 END
										WHEN @TIP = 1 THEN CASE WHEN EKRAN_GIRIS_SENARYOSU IN (4,5) THEN 1 ELSE 0 END
										ELSE 0
									END,
			@CARI_HAREKET_URET = CASE WHEN @TIP = 1 AND ALT_TUR = 0 THEN ISNULL(HESAP_HAREKETI_URET,0) ELSE 0 END
		FROM TOHOM_EVRAK_KONUSU
		WHERE EVRAK_KONUSU_ID = @EVRAK_KONUSU_ID
	DECLARE @IS_NESNESI_ID KAYIT_ID
	DECLARE @GERCEK_IS_NESNESI_ID KAYIT_ID
	IF @IPTAL_FISI = 1 SET @GERCEK_IS_NESNESI_ID = CASE WHEN @TIP = 0 THEN 134 ELSE 135 END
	ELSE IF @TIP = 0 SET @GERCEK_IS_NESNESI_ID = CASE WHEN @ONCEKI_ID IS NULL THEN 1 ELSE 32 END /*Malzeme sözleşmesi*/
	ELSE IF @TIP = 1 SET @GERCEK_IS_NESNESI_ID = 2
	ELSE IF @TIP = 2 SET @GERCEK_IS_NESNESI_ID = 24
	SET @IS_NESNESI_ID = NULL
	IF @IPTAL_FISI = 0
	BEGIN
		SELECT @IS_NESNESI_ID = IS_NESNESI_ID FROM TOHOM_EVRAK_KONUSU WHERE EVRAK_KONUSU_ID = @EVRAK_KONUSU_ID
		IF @IS_NESNESI_ID IS NULL SET @IS_NESNESI_ID = @GERCEK_IS_NESNESI_ID
	END
	ELSE SET @IS_NESNESI_ID = @GERCEK_IS_NESNESI_ID
	IF @IS_NESNESI_ID IS NULL SET @ONAYLANDI = 1
	ELSE IF @DENETIM_ISLEMI = 4 OR EXISTS(SELECT * FROM TOHOM_KULLANICI WHERE KULLANICI_ID = @KULLANICI_ID AND SISTEM_YONETICISI = 1)
	BEGIN
		IF @YENI_KAYIT = 0 SELECT @ONAYLANDI = ONAYLANDI FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
		ELSE SET @ONAYLANDI = 1
	END
	ELSE IF @DENETIM_ISLEMI = 0
	BEGIN
		IF EXISTS(SELECT * FROM TOHOM_ONAY_TALEBI WHERE TUR = 0 AND ILGILI_ID = @SIPARIS_ID AND ILGI_CINSI = @IS_NESNESI_ID AND STATU = 2) SET @ONAY_DURUMU = 2
		IF EXISTS(SELECT * FROM TOHOM_ONAY_TALEBI WHERE TUR = 0 AND ILGILI_ID = @SIPARIS_ID AND ILGI_CINSI = @IS_NESNESI_ID AND STATU = 0) SET @ONAY_DURUMU = 1
		EXEC @DONUS_KODU = SOHOMROL_SIPARIS_DENETLE @SIPARIS_ID, @PARTI_YAMASI_ID, @TIP, @EVRAK_KONUSU_ID, @SIPARIS_NO,
			@TARIH, @OPSIYON_TARIHI, @KUR_TARIHI, @PARA_ID, @KUR, @KARSI_REF_NO, @ONCELIK_ID, @TOPLAM_TUTAR,
			@ISKONTO_ORANI,  @ISKONTO_HESAPLANMASIN, @ISKONTO, @ISKONTO_TOPLAMI, @KDV_ORANI, @HESAPLANAN_ORTALAMA_VADE,
			@ACIKLAMA, @ILGI_CINSI, @ILGILI_ID, @IPTAL_FISI, @ODEME_PLANI_ID, @ORTALAMA_VADE, @ORTALAMA_VADE_BIRIMI, @VALOR_ZAMANI,
			@VALOR_ZAMAN_BIRIMI, @VADE_FARKI_ORANI, @VADE_FARKI_ZAMAN_BIRIMI, @MUHATAP_BANKA_ID,
			@FIRMAMIZ_BANKA_HESAP_ID, @ODEME_YETKILISI_ID, @ODEME_ADRESI, @TICARET_SEKLI, @TESLIMAT_YETKILISI_ID,
			@TESLIMAT_ADRESI, @TESLIMAT_BICIMI, @TESLIMAT_SEKLI_ID, @TESLIMAT_SURESI, @TESLIMAT_SURESI_BIRIMI,
			@YOLA_CIKIS_TARIHI, @YUKLEME_YERI, @YUKLEME_TARIHI, @VARACAGI_YER, @TAHMINI_VARIS_TARIHI, @NAKLIYATCI_ID,
			@NAKLIYATCI_ACENTA_ID, @NAKLIYAT_SIGORTASINI_USTLENEN, @NAKLIYAT_SIGORTACISI_ID,
			@NAKLIYAT_SIGORTACISI_ACENTA_ID, @GUMRUKCU_ID, @ULASIM_SEKLI_ID, @ULASIM_DETAYI, @KOMISYONCU_ID,
			@KOMISYON_ORANI, @FATURA_YETKILISI_ID, @FATURA_ADRESI, @HAKKINDA, @NOT1, @NOT2, @NOT3, @ONCEKI_ID,
			@KEFIL_ID, @IHZARAT_ODEME_ORANI, @SOZLESME_KONUSU, @ZEYILNAME_KONUSU, @SOZLESME_BASLANGIC_TARIHI, @SOZLESME_BITIS_TARIHI,
			@SAHIP_TURU, @SAHIP_ID, @KDV_TEVKIFAT_TANIMI_ID, @NIHAI_MUSTERI_ID, @SIPARIS_TURU, @SOZLESME_TURU,
			@ALIM_YERI, @SECILEN_FIRMA_ID, @KDV_DURUMU, @GARANTI_SURESI, @GARANTI_SURESI_BIRIMI,
			@GARANTI_VEREN_ID, @KUR_TIPI, @FIYATLANDIRMA_BICIMI, @NAKLIYE_UCRETI_DAHIL, @NAKLIYE_UCRETI, @NAKLIYE_UCRETI_PARA_ID,
			@BARTER_FATURALAMA_SEKLI, @GECICI_IHRACAT_ICINDIR, @SATINALAN_SUBE_ID, @SATINALMA_BEDELI, @UYGULAYAN_SUBE_ID, @UYGULAMA_BEDELI, @SGK_ISCILIK_ORANI,
			@DOKUMANI_VAR, @KAR_ORANI,
			@KULLANICI_ID, @GUID, @DENETIM_ISLEMI, @IS_NESNESI_ID, @YENI_KAYIT, @PROJEMIZ_ID, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1
		BEGIN
			DELETE FROM #TOHOM_ISKELE_SINIRLAMA
			GOTO UNDO
		END
		IF EXISTS(SELECT * FROM #TOHOM_ISKELE_SINIRLAMA) OR @ONAY_DURUMU <> 0 RETURN 2
		IF @YENI_KAYIT = 0 SELECT @ONAYLANDI = ONAYLANDI FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
		ELSE SET @ONAYLANDI = 1
	END
	ELSE IF @YENI_KAYIT = 0 AND @DENETIM_ISLEMI = 6 SELECT @ONAYLANDI = ONAYLANDI FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
	ELSE IF @YENI_KAYIT = 1 AND @DENETIM_ISLEMI = 7 SET @ONAYLANDI = 0
	ELSE IF NOT EXISTS(SELECT * FROM #TOHOM_ISKELE_SINIRLAMA WHERE SINIRLAMA_TURU = 1)
	BEGIN
		IF @YENI_KAYIT = 0 SELECT @ONAYLANDI = ONAYLANDI FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
		ELSE SET @ONAYLANDI = 1
	END
	ELSE SET @ONAYLANDI = 0
	IF @TIP = 0 AND @SIPARIS_ALT_TUR = 5
	BEGIN
		IF EXISTS(SELECT COUNT(*)
					FROM
					(SELECT PROJEMIZ_ID, MASRAF_MERKEZI_ID
						FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI
						WHERE GUID = @GUID AND SATIR_TURU = 0
						GROUP BY PROJEMIZ_ID, MASRAF_MERKEZI_ID
					) AS X
					HAVING COUNT(*) > 1
				)
		BEGIN
			SET @HATA_NO = 62253
			GOTO UNDO
		END
	END
	ELSE IF @TIP = 2
	BEGIN
		IF @SIPARIS_ALT_TUR = 4		/* DEPO TALEBI*/
		BEGIN
			IF EXISTS(SELECT *
							FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK
								INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_SATIRI_ID = ISK.ONCEKI_ID
								INNER JOIN TOHOM_SIPARIS S ON S.SIPARIS_ID = SS.SIPARIS_ID
								INNER JOIN TOHOM_EVRAK_KONUSU EK ON EK.EVRAK_KONUSU_ID = S.EVRAK_KONUSU_ID
								INNER JOIN TOHOM_ONAY_TALEBI T ON T.ILGI_CINSI = ISNULL(EK.IS_NESNESI_ID, 24) AND T.ILGILI_ID = S.SIPARIS_ID
							WHERE ISK.GUID = @GUID AND S.ONAYLANDI = 1)
			BEGIN
				SET @HATA_NO = 60615
				GOTO UNDO
			END
		END
		ELSE IF @YENI_KAYIT = 0		/* Talep değişikliği*/
		BEGIN
			DECLARE C_SATIR CURSOR STATIC LOCAL FOR
				SELECT SS.MIKTAR, ISNULL(ISK.MIKTAR,0), ISNULL(DTS.TOPLAM_MIKTAR,0)
					FROM TOHOM_SIPARIS_SATIRI SS
						LEFT OUTER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = SS.SIPARIS_SATIRI_ID AND ISK.GUID = @GUID
						LEFT OUTER JOIN VOHOM_00_DAHILI_TALEP_SATIRI_DEPO_TALEBI_MIKTARI DTS ON DTS.ONCEKI_ID = SS.SIPARIS_SATIRI_ID
					WHERE SS.SIPARIS_ID = @SIPARIS_ID
			DECLARE @ESKI_MIKTAR MIKTAR
			DECLARE @YENI_MIKTAR MIKTAR
			DECLARE @REZERVE_MIKTAR MIKTAR
			OPEN C_SATIR
			FETCH NEXT FROM C_SATIR INTO @ESKI_MIKTAR, @YENI_MIKTAR, @REZERVE_MIKTAR
			WHILE @@FETCH_STATUS = 0
			BEGIN
				IF (@YENI_MIKTAR < @ESKI_MIKTAR) AND (@YENI_MIKTAR < @REZERVE_MIKTAR)
				BEGIN
					SET @HATA_NO = 60616
					CLOSE C_SATIR
					GOTO UNDO
				END
				FETCH NEXT FROM C_SATIR INTO @ESKI_MIKTAR, @YENI_MIKTAR, @REZERVE_MIKTAR
			END
			CLOSE C_SATIR
		END
	END
	IF @SIPARIS_ALT_TUR = 3
	BEGIN
		DELETE DG
			FROM TOHOM_SOZLESME_PROJE_DAGILIMI DG
				LEFT OUTER JOIN
				(SELECT PROJEMIZ_ID
					FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI
					WHERE GUID = @GUID
					GROUP BY PROJEMIZ_ID
				) AS PX ON PX.PROJEMIZ_ID = DG.PROJEMIZ_ID
			WHERE SOZLESME_ID = @SIPARIS_ID AND PX.PROJEMIZ_ID IS NULL
	END
	DECLARE @TALEP_NO KOD
	DECLARE @IPTAL_SAYISI INT
	IF (@SIPARIS_NO IS NULL OR LEN(@SIPARIS_NO) = 0) /* Sipariş numaratörü*/
	BEGIN
		IF (@TIP = 0)
		BEGIN
			IF (@IPTAL_FISI = 0)
			BEGIN
				DECLARE @SOZLESME_NO KOD
				DECLARE @SOZLESME_ID KAYIT_ID
				SELECT @SOZLESME_ID = OSP.SIPARIS_ID, @SOZLESME_NO = OSP.SIPARIS_NO
					FROM TOHOM_SIPARIS OSP
						INNER JOIN TOHOM_EVRAK_KONUSU K ON K.EVRAK_KONUSU_ID = OSP.EVRAK_KONUSU_ID
					WHERE OSP.SIPARIS_ID = @ONCEKI_ID AND K.ALT_TUR = 2
				IF @SOZLESME_NO IS NOT NULL
				BEGIN
					DECLARE @MAX_LEN INT
					SELECT @MAX_LEN = MAX(LEN(SIPARIS_NO))
						FROM TOHOM_SIPARIS
						WHERE ONCEKI_ID = @SOZLESME_ID AND SIPARIS_ID <> ISNULL(@SIPARIS_ID,0)
					SELECT @SIPARIS_NO = MAX(SIPARIS_NO)
						FROM TOHOM_SIPARIS
						WHERE ONCEKI_ID = @SOZLESME_ID AND SIPARIS_ID <> ISNULL(@SIPARIS_ID,0) AND LEN(SIPARIS_NO) = @MAX_LEN
					EXEC SOHOM_BAGLI_EVRAK_NO_URET @SOZLESME_NO, 'SA', @SIPARIS_NO, NULL, @SIPARIS_NO OUT
				END
				IF @SIPARIS_NO IS NULL
					EXEC SOHOM_NUMERATOR_URET 7, @SIPARIS_NO OUT, @EVRAK_KONUSU_ID, @PROJEMIZ_ID /*verilen sipariş*/
			END
			ELSE IF (@IPTAL_FISI = 1 AND @ONCEKI_ID IS NOT NULL)
			BEGIN
				IF ISNULL(@SIPARIS_ID,0) = 0
					SELECT @IPTAL_SAYISI = COUNT(*) FROM TOHOM_SIPARIS WHERE IPTAL_FISI = 1 AND ONCEKI_ID = @ONCEKI_ID
				ELSE
					SELECT @IPTAL_SAYISI = COUNT(*) FROM TOHOM_SIPARIS WHERE IPTAL_FISI = 1 AND ONCEKI_ID = @ONCEKI_ID AND SIPARIS_ID < @SIPARIS_ID
				SELECT @SIPARIS_NO = SIPARIS_NO FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @ONCEKI_ID
				SET @IPTAL_SAYISI = ISNULL(@IPTAL_SAYISI,0)+1
				SET @SIPARIS_NO = RTRIM(ISNULL(@SIPARIS_NO,'')) + '.I' + REPLACE(STR(@IPTAL_SAYISI,2,0),' ','0')
			END
			ELSE  EXEC SOHOM_NUMERATOR_URET 9, @SIPARIS_NO OUT/* verilen sipariş iptal fişi*/
		END
		ELSE IF (@TIP = 1)
		BEGIN
			IF (@IPTAL_FISI = 0)
				EXEC SOHOM_NUMERATOR_URET 6, @SIPARIS_NO OUT, @EVRAK_KONUSU_ID, @PROJEMIZ_ID /* alınan sipariş */
			ELSE IF (@IPTAL_FISI = 1 AND @ONCEKI_ID IS NOT NULL)
			BEGIN
				IF ISNULL(@SIPARIS_ID,0) = 0
					SELECT @IPTAL_SAYISI = COUNT(*) FROM TOHOM_SIPARIS WHERE IPTAL_FISI = 1 AND ONCEKI_ID = @ONCEKI_ID
				ELSE
					SELECT @IPTAL_SAYISI = COUNT(*) FROM TOHOM_SIPARIS WHERE IPTAL_FISI = 1 AND ONCEKI_ID = @ONCEKI_ID AND SIPARIS_ID < @SIPARIS_ID
				SELECT @SIPARIS_NO = SIPARIS_NO FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @ONCEKI_ID
				SET @IPTAL_SAYISI = ISNULL(@IPTAL_SAYISI,0)+1
				SET @SIPARIS_NO = RTRIM(ISNULL(@SIPARIS_NO,'')) + '.I' + REPLACE(STR(@IPTAL_SAYISI,2,0),' ','0')
			END
			ELSE EXEC SOHOM_NUMERATOR_URET 8, @SIPARIS_NO OUT/* alınan sipariş iptal fişi */
		END
		ELSE IF @TIP = 2
		BEGIN
			DECLARE @TALEP_ID KAYIT_ID
			SELECT @TALEP_ID = OSP.SIPARIS_ID, @TALEP_NO = OSP.SIPARIS_NO
				FROM TOHOM_SIPARIS OSP
				WHERE OSP.SIPARIS_ID = @ONCEKI_ID AND TIP = 2
			IF @TALEP_NO IS NOT NULL
			BEGIN
				SELECT @SIPARIS_NO = MAX(SIPARIS_NO)
					FROM TOHOM_SIPARIS
					WHERE ONCEKI_ID = @TALEP_ID
				EXEC SOHOM_BAGLI_EVRAK_NO_URET @TALEP_NO, '', @SIPARIS_NO, NULL, @SIPARIS_NO OUT
			END
			IF @SIPARIS_NO IS NULL
				EXEC SOHOM_NUMERATOR_URET 47, @SIPARIS_NO OUT, @EVRAK_KONUSU_ID, @PROJEMIZ_ID /* dahili talep formu */
		END
	END
	DECLARE @OTV_VAR BOOL
	SET @OTV_VAR = 1
	IF @SIPARIS_TURU = 1 AND ROUND(@KDV_ORANI, 3) = 0.0 AND NOT EXISTS(SELECT * FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI WHERE GUID = @GUID AND ROUND(KDV_ORANI, 3) > 0.0)
		SET @OTV_VAR = 0
	DELETE TOHOM_ISKELE_XID WHERE GUID = @GUID
	DECLARE @ESKI_AVANS_YONETIMI_UYGULANSIN	BOOL
	IF @YENI_KAYIT = 0 AND EXISTS(SELECT name FROM sysobjects WHERE type = 'P' and name = 'S_SiparisKaydetmedenOnce')
	BEGIN
		EXEC @DONUS_KODU = S_SiparisKaydetmedenOnce @SIPARIS_ID, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
	END
	IF (@YENI_KAYIT = 1)
	BEGIN
		INSERT INTO TOHOM_SIPARIS (	PARTI_YAMASI_ID,
							TIP,
							EVRAK_KONUSU_ID,
							SIPARIS_TURU,
							SIPARIS_NO,
							TARIH,
							OPSIYON_TARIHI,
							KUR_TARIHI,
							PARA_ID,
							KUR,
							KARSI_REF_NO,
							ONCELIK_ID,
							TOPLAM_TUTAR,
							ISKONTO_ORANI,
							ISKONTO_HESAPLANMASIN,
							ISKONTO,
							ISKONTO_TOPLAMI,
							RUSUM_TOPLAMI,
							BEYAN_EDILECEK_OTV,
							RUSUM_KDV_MATRAHINA_DAHIL,
							KDV_ORANI,
							HESAPLANAN_ORTALAMA_VADE,
							IHZARAT_ODEME_ORANI,
							ACIKLAMA,
							SOZLESME_KONUSU,
							ZEYILNAME_KONUSU,
							SOZLESME_BASLANGIC_TARIHI,
							SOZLESME_BITIS_TARIHI,
							ILGI_CINSI,
							ILGILI_ID,
							IPTAL_FISI,
							EKLEYEN_ID,
							EKLEME_ZAMANI,
							GUNCELLEYEN_ID,
							GUNCELLEME_ZAMANI,
							ONAYLANDI,
							ONCEKI_ID,
							SAHIP_TURU,
							SAHIP_ID,
							ANALIZ_TIPI,
							ALIM_YERI,
							SECILEN_FIRMA_ID,
							KDV_DURUMU,
							KUR_TIPI,
							FIYATLANDIRMA_BICIMI,
							BARTER_FATURALAMA_SEKLI,
							GECICI_IHRACAT_ICINDIR,
							SATINALAN_SUBE_ID,
							SATINALMA_BEDELI,
							UYGULAYAN_SUBE_ID,
							UYGULAMA_BEDELI,
							SGK_ISCILIK_ORANI,
							ZEYILNAME_NO,
							ODEME_PLANI_HAKKINDA,
							ISCILIK_AZAMI_KAR_ORANI,
							FATURA_UYGULANAN_PARA_SECIMI,
							KAR_ORANI,
							DURUM_ID,
							ALT_HESAP_ID,
							FIYAT_FARKI_INDEKS_ID,
							FIYAT_FARKI_ORANI,
							IDARE_KESINTI_ORANI,
							METRAJ_GIRIS_SEKLI)
			VALUES (@PARTI_YAMASI_ID,
					@TIP,
					@EVRAK_KONUSU_ID,
					@SIPARIS_TURU,
					@SIPARIS_NO,
					@TARIH,
					@OPSIYON_TARIHI,
					@KUR_TARIHI,
					@PARA_ID,
					@KUR,
					@KARSI_REF_NO,
					@ONCELIK_ID,
					@TOPLAM_TUTAR,
					@ISKONTO_ORANI,
					@ISKONTO_HESAPLANMASIN,
					@ISKONTO,
					@ISKONTO_TOPLAMI,
					CASE WHEN @OTV_VAR = 1 THEN @RUSUM_TOPLAMI ELSE 0.0 END,
					@RUSUM_TOPLAMI,
					@RUSUM_KDV_MATRAHINA_DAHIL,
					@KDV_ORANI,
					@HESAPLANAN_ORTALAMA_VADE,
					@IHZARAT_ODEME_ORANI,
					@ACIKLAMA,
					@SOZLESME_KONUSU,
					@ZEYILNAME_KONUSU,
					@SOZLESME_BASLANGIC_TARIHI,
					@SOZLESME_BITIS_TARIHI,
					@ILGI_CINSI,
					@ILGILI_ID,
					@IPTAL_FISI,
					@KULLANICI_ID,
					@ZAMAN,
					@KULLANICI_ID,
					@ZAMAN,
					@ONAYLANDI,
					@ONCEKI_ID,
					@SAHIP_TURU,
					@SAHIP_ID,
					@SOZLESME_TURU,
					@ALIM_YERI,
					@SECILEN_FIRMA_ID,
					@KDV_DURUMU,
					@KUR_TIPI,
					@FIYATLANDIRMA_BICIMI,
					@BARTER_FATURALAMA_SEKLI,
					@GECICI_IHRACAT_ICINDIR,
					@SATINALAN_SUBE_ID,
					@SATINALMA_BEDELI,
					@UYGULAYAN_SUBE_ID,
					@UYGULAMA_BEDELI,
					@SGK_ISCILIK_ORANI,
					0,
					@ODEME_PLANI_HAKKINDA,
					@ISCILIK_AZAMI_KAR_ORANI,
					@FATURA_UYGULANAN_PARA_SECIMI,
					@KAR_ORANI,
					@DURUM_ID,
					@ALT_HESAP_ID,
					@FIYAT_FARKI_INDEKS_ID,
					@FIYAT_FARKI_ORANI,
					@IDARE_KESINTI_ORANI,
					@METRAJ_GIRIS_SEKLI)
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60120
			GOTO UNDO
		END
		SELECT @SIPARIS_ID = @@IDENTITY
		INSERT INTO TOHOM_ISKELE_XID(GUID, XID) VALUES(@GUID, @SIPARIS_ID)
		UPDATE TOHOM_SIPARIS SET ACIKLAMA = @ACIKLAMA WHERE SIPARIS_ID = @SIPARIS_ID
	END
	ELSE BEGIN
		SELECT @ESKI_AVANS_YONETIMI_UYGULANSIN = ESKI_AVANS_YONETIMI_UYGULANSIN FROM TOHOM_SIPARIS WHERE SIPARIS_ID =  @SIPARIS_ID
		IF @TIP = 0 AND @SIPARIS_ALT_TUR = 5
			AND NOT EXISTS(SELECT *
							FROM
								(SELECT TARIH, SUM(ANAPARA + FAIZ) AS TAKSIT
									FROM TOHOM_KREDI_ODEME_PLANI
									WHERE SAHIP_TURU = 0 AND SAHIP_ID = @SIPARIS_ID
									GROUP BY TARIH
								) AS O
								FULL OUTER JOIN
								(SELECT TARIH, SUM(ANAPARA + FAIZ) AS TAKSIT
									FROM TOHOM_ISKELE_KREDI_ODEME_PLANI
									WHERE GUID = @GUID
									GROUP BY TARIH
								) AS S ON S.TARIH = O.TARIH
								, TOHOM_PARA PR
							WHERE PR.PARA_ID = @PARA_ID AND ROUND(ISNULL(O.TAKSIT, 0.0) - ISNULL(S.TAKSIT, 0.0), PR.KURUS_BASAMAK_SAYISI) <> 0.0)
			SET @HESAP_HAREKETI_URET = 0
		INSERT INTO TOHOM_ISKELE_XID(GUID, XID) VALUES(@GUID, @SIPARIS_ID)
		DELETE FROM TOHOM_EVRAK_DETAYI WHERE EVRAK_TURU = 2  AND  EVRAK_ID=@SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60122
			GOTO UNDO
		END
		DELETE FROM TOHOM_EVRAK_DETAYI WHERE EVRAK_TURU = 3 AND EVRAK_ID  IN ( SELECT SIPARIS_SATIRI_ID FROM TOHOM_SIPARIS_SATIRI WHERE SIPARIS_ID = @SIPARIS_ID)
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60122
			GOTO UNDO
		END
		DELETE FROM TOHOM_EVRAK_VERGISI WHERE EVRAK_TURU =2  AND EVRAK_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60103
			GOTO UNDO
		END
		DELETE FROM TOHOM_OZELLIK_DEGERI WHERE SAHIP_TURU = 10 AND SAHIP_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60339
			GOTO UNDO
		END
		DELETE FROM TOHOM_OZELLIK_DEGERI WHERE SAHIP_TURU = 3 AND SAHIP_ID IN ( SELECT SIPARIS_SATIRI_ID FROM TOHOM_SIPARIS_SATIRI WHERE SIPARIS_ID = @SIPARIS_ID)
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60339
			GOTO UNDO
		END
		IF @TIP <> 1 OR @SENARYO <> 3 /*Konfeksiyon üretim satış siparişinde envanter ekranda satır detayında kaydediliyor*/
		BEGIN
			DELETE FROM TOHOM_ENVANTER_SATIRI_YATAY WHERE SAHIP_TURU = 2 AND SAHIP_ID IN ( SELECT SIPARIS_SATIRI_ID FROM TOHOM_SIPARIS_SATIRI WHERE SIPARIS_ID = @SIPARIS_ID)
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60415
				GOTO UNDO
			END
		END
		DELETE F
			FROM TOHOM_SIPARIS_URUN_FIYATI F
				INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SIPARIS_SATIRI_ID = F.SIPARIS_SATIRI_ID
			WHERE S.SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60488
			GOTO UNDO
		END
		IF @TIP = 2
		BEGIN
			DELETE BG
				FROM TOHOM_TALEP_SIPARIS_BAGI BG
					INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SIPARIS_SATIRI_ID = BG.TALEP_SATIRI_ID
				WHERE S.SIPARIS_ID = @SIPARIS_ID
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60751
				GOTO UNDO
			END
		END
		ELSE BEGIN
			DELETE P
				FROM TOHOM_TESLIMAT_PLANI P
					INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SIPARIS_SATIRI_ID = P.SAHIP_ID
				WHERE S.SIPARIS_ID = @SIPARIS_ID AND P.SAHIP_TURU = 1
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60488
				GOTO UNDO
			END
		END
		/* veritabanında olup da iskelede yer almayanları silelim.*/
		DELETE S
			FROM TOHOM_SIPARIS_SATIRI S
				LEFT OUTER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = S.SIPARIS_SATIRI_ID AND ISK.GUID = @GUID
			WHERE S.SIPARIS_ID = @SIPARIS_ID AND ISK.SATIR_ID IS NULL
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60123
			GOTO UNDO
		END
		DELETE S
			FROM TOHOM_ODEME_PLANI_SATIRI S
				LEFT OUTER JOIN TOHOM_ISKELE_ODEME_PLANI_SATIRI ISK ON ISK.ODEME_PLANI_SATIRI_ID = S.ODEME_PLANI_SATIRI_ID AND ISK.GUID = @GUID
			WHERE S.SAHIP_TURU = 23 AND S.SAHIP_ID = @SIPARIS_ID AND ISK.ODEME_PLANI_SATIRI_ID IS NULL
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 6060
			GOTO UNDO
		END
		DELETE FROM TOHOM_KREDI_ODEME_PLANI WHERE SAHIP_TURU = 0 AND SAHIP_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 6060
			GOTO UNDO
		END
		DELETE FROM TOHOM_SIPARIS_KESINTISI WHERE SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60601
			GOTO UNDO
		END
		DELETE FROM TOHOM_EVRAK_TEMINATI WHERE EVRAK_TURU = 2 AND EVRAK_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60657
			GOTO UNDO
		END
		DELETE FROM TOHOM_SIPARIS_SORUMLUSU WHERE SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60677
			GOTO UNDO
		END
		IF @SIPARIS_ALT_TUR = 3
		BEGIN
			DELETE DG
				FROM TOHOM_SOZLESME_PROJE_DAGILIMI DG
					LEFT OUTER JOIN
					(SELECT PROJEMIZ_ID
						FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI
						WHERE GUID = @GUID
						GROUP BY PROJEMIZ_ID
					) AS PX ON PX.PROJEMIZ_ID = DG.PROJEMIZ_ID
				WHERE SOZLESME_ID = @SOZLESME_ID AND PX.PROJEMIZ_ID IS NULL
		END
		UPDATE TOHOM_SIPARIS
			SET 	PARTI_YAMASI_ID = @PARTI_YAMASI_ID,
				TIP = @TIP,
				EVRAK_KONUSU_ID = @EVRAK_KONUSU_ID,
				SIPARIS_TURU = @SIPARIS_TURU,
				SIPARIS_NO = @SIPARIS_NO,
				TARIH = @TARIH,
				OPSIYON_TARIHI = @OPSIYON_TARIHI,
				KUR_TARIHI = @KUR_TARIHI,
				PARA_ID = @PARA_ID,
				KUR = @KUR,
				KARSI_REF_NO = @KARSI_REF_NO,
				ONCELIK_ID = @ONCELIK_ID,
				TOPLAM_TUTAR = @TOPLAM_TUTAR,
				ISKONTO_ORANI = @ISKONTO_ORANI,
				ISKONTO = @ISKONTO,
				ISKONTO_HESAPLANMASIN = @ISKONTO_HESAPLANMASIN,
				ISKONTO_TOPLAMI = @ISKONTO_TOPLAMI,
				RUSUM_TOPLAMI = CASE WHEN @OTV_VAR = 1 THEN @RUSUM_TOPLAMI ELSE 0.0 END,
				BEYAN_EDILECEK_OTV = @RUSUM_TOPLAMI,
				RUSUM_KDV_MATRAHINA_DAHIL = @RUSUM_KDV_MATRAHINA_DAHIL,
				KDV_ORANI = @KDV_ORANI,
				HESAPLANAN_ORTALAMA_VADE = @HESAPLANAN_ORTALAMA_VADE,
				IHZARAT_ODEME_ORANI = @IHZARAT_ODEME_ORANI,
				ACIKLAMA = @ACIKLAMA,
				SOZLESME_KONUSU = @SOZLESME_KONUSU,
				ZEYILNAME_KONUSU = @ZEYILNAME_KONUSU,
				SOZLESME_BASLANGIC_TARIHI = @SOZLESME_BASLANGIC_TARIHI,
				SOZLESME_BITIS_TARIHI = @SOZLESME_BITIS_TARIHI,
				ILGI_CINSI = @ILGI_CINSI,
				ILGILI_ID = @ILGILI_ID,
				IPTAL_FISI = @IPTAL_FISI,
				GUNCELLEYEN_ID = @KULLANICI_ID,
				GUNCELLEME_ZAMANI = @ZAMAN,
				ONAYLANDI = @ONAYLANDI,
				ONCEKI_ID = @ONCEKI_ID,
				SAHIP_TURU = @SAHIP_TURU,
				SAHIP_ID = @SAHIP_ID,
				ANALIZ_TIPI = @SOZLESME_TURU,
				ALIM_YERI = @ALIM_YERI,
				SECILEN_FIRMA_ID = @SECILEN_FIRMA_ID,
				KDV_DURUMU = @KDV_DURUMU,
				KUR_TIPI = @KUR_TIPI,
				FIYATLANDIRMA_BICIMI = @FIYATLANDIRMA_BICIMI,
				BARTER_FATURALAMA_SEKLI = @BARTER_FATURALAMA_SEKLI,
				GECICI_IHRACAT_ICINDIR = @GECICI_IHRACAT_ICINDIR,
				SATINALAN_SUBE_ID = @SATINALAN_SUBE_ID,
				SATINALMA_BEDELI = @SATINALMA_BEDELI,
				UYGULAYAN_SUBE_ID = @UYGULAYAN_SUBE_ID,
				UYGULAMA_BEDELI = @UYGULAMA_BEDELI,
				SGK_ISCILIK_ORANI = @SGK_ISCILIK_ORANI,
				ODEME_PLANI_HAKKINDA = @ODEME_PLANI_HAKKINDA,
				ISCILIK_AZAMI_KAR_ORANI = @ISCILIK_AZAMI_KAR_ORANI,
				FATURA_UYGULANAN_PARA_SECIMI = @FATURA_UYGULANAN_PARA_SECIMI,
				KAR_ORANI = @KAR_ORANI,
				DURUM_ID = @DURUM_ID,
				ALT_HESAP_ID = @ALT_HESAP_ID,
				FIYAT_FARKI_INDEKS_ID = @FIYAT_FARKI_INDEKS_ID,
				FIYAT_FARKI_ORANI = @FIYAT_FARKI_ORANI,
				IDARE_KESINTI_ORANI = @IDARE_KESINTI_ORANI,
				METRAJ_GIRIS_SEKLI = @METRAJ_GIRIS_SEKLI
			WHERE SIPARIS_ID=@SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60124
			GOTO UNDO
		END
	END
	/*Satir duplikasyonu olmasın diye önce olmayan satırlar silinir. Var olan satırlar eklenir. En sonda yeni satırlar eklenir.*/
	IF @YENI_KAYIT = 0
	BEGIN
		/*değişen ürün, birim ile ilgili bağları silelim*/
		IF @IPTAL_FISI = 0
		BEGIN
			UPDATE S SET SIPARIS_SATIRI_ID = NULL
				FROM TOHOM_FATURA_SATIRI S
					INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_SATIRI_ID = S.SIPARIS_SATIRI_ID
					INNER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = SS.SIPARIS_SATIRI_ID
				WHERE ISK.GUID = @GUID AND (ISK.URUN_YAMASI_ID <> SS.URUN_YAMASI_ID OR ISK.BIRIM_ID <> SS.BIRIM_ID )
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60217
				GOTO UNDO
			END
			UPDATE S SET IPTAL_SATIRI_ID = NULL
				FROM TOHOM_SIPARIS_SATIRI S
					INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_SATIRI_ID = S.IPTAL_SATIRI_ID
					INNER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = SS.SIPARIS_SATIRI_ID
				WHERE ISK.GUID = @GUID AND (ISK.URUN_YAMASI_ID <> SS.URUN_YAMASI_ID OR ISK.BIRIM_ID <> SS.BIRIM_ID )
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60217
				GOTO UNDO
			END
			UPDATE S SET SIPARIS_SATIRI_ID = NULL
				FROM TOHOM_DEPO_FISI_SATIRI S
					INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_SATIRI_ID = S.SIPARIS_SATIRI_ID
					INNER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = SS.SIPARIS_SATIRI_ID
				WHERE ISK.GUID = @GUID AND (ISK.URUN_YAMASI_ID <> SS.URUN_YAMASI_ID OR ISK.BIRIM_ID <> SS.BIRIM_ID )
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60217
				GOTO UNDO
			END
		END
		/* hem iskelede hem de veritabanında olanları güncelleyelim*/
		UPDATE S SET 	SATIR_NO = ISK.SATIR_NO,
				SATIR_TURU = ISK.SATIR_TURU,
				KALEM_NO = ISK.KALEM_NO,
				URUN_YAMASI_ID = ISK.URUN_YAMASI_ID,
				DARA = ISK.DARA,
				DARA_BIRIMI_ID = ISK.DARA_BIRIMI_ID,
				MIKTAR = ISK.MIKTAR,
				BIRIM_ID = ISK.BIRIM_ID,
				ALAN = ISK.ALAN,
				ALAN_BIRIM_FIYATI = ISK.ALAN_BIRIM_FIYATI,
				KIRA_CIRO_ORANI = ISK.KIRA_CIRO_ORANI,
				BIRIM_FIYATI = ISK.BIRIM_FIYATI,
				PARA_ID = ISK.PARA_ID,
				NAKLIYE_MALZEME_FIYATI = ISK.NAKLIYE_MALZEME_FIYATI,
				NAKLIYE_MALZEME_PARA_ID = ISK.NAKLIYE_MALZEME_PARA_ID,
				KUR = ISK.KUR,
				TUTAR_HESAPLANMASIN = ISK.TUTAR_HESAPLANMASIN,
				TUTAR = ISK.TUTAR,
				KDVSIZ_TUTAR = ISK.KDVSIZ_TUTAR,
				ISKONTO_ORANI = ISK.ISKONTO_ORANI,
				ISKONTO_HESAPLANMASIN = ISK.ISKONTO_HESAPLANMASIN,
				ISKONTO = ISK.ISKONTO,
				ISKONTO_PAYI = ISK.ISKONTO_PAYI,
				RUSUM_ORANI = ISK.RUSUM_ORANI,
				RUSUM_HESAPLANMASIN = ISK.RUSUM_HESAPLANMASIN,
				RUSUM = CASE WHEN @OTV_VAR = 1 THEN ISK.RUSUM ELSE 0.0 END,
				BEYAN_EDILECEK_OTV = ISK.RUSUM,
				KDV_FIYATA_DAHIL = ISK.KDV_FIYATA_DAHIL,
				KDV_ORANI = ISK.KDV_ORANI,
				ONCEKI_ID = ISK.ONCEKI_ID,
				TEKLIF_SATIRI_ID = ISK.XID_1,
				IPTAL_SATIRI_ID = CASE WHEN @IPTAL_FISI = 1 THEN ISK.XID_2 ELSE NULL END,
				KAPANDI = ISK.KAPANDI,
				FIYAT2 = ISK.FIYAT2,
				PARA2_ID = ISK.PARA2_ID,
				KUR2 = ISK.KUR2,
				TUTAR2 = ISK.TUTAR2,
				FIYAT3 = ISK.FIYAT3,
				PARA3_ID = ISK.PARA3_ID,
				KUR3 = ISK.KUR3,
				TUTAR3 = ISK.TUTAR3,
				GENEL_GIDER_PAYI = ISK.GENEL_GIDER_PAYI,
				GENEL_GIDER_PAYI_PARA_ID = ISK.GENEL_GIDER_PAYI_PARA_ID,
				GENEL_GIDER_KURU = ISK.GENEL_GIDER_KURU,
				KAR_PAYI = ISK.KAR_PAYI,
				KAR_PAYI_PARA_ID = ISK.KAR_PAYI_PARA_ID,
				KAR_KURU = ISK.KAR_KURU,
				PROJEMIZ_ID = ISK.PROJEMIZ_ID,
				AKTIVITE_ID = ISK.AKTIVITE_ID,
				MASRAF_MERKEZI_ID = ISK.MASRAF_MERKEZI_ID,
				BUTCE_KALEMI_ID = ISK.BUTCE_KALEMI_ID,
				BUTCE_BOLUMU_ID = ISK.BUTCE_BOLUMU_ID,
				LISTE_FIYATI = ISK.LISTE_FIYATI,
				LISTE_FIYATI_PARA_ID = ISK.LISTE_FIYATI_PARA_ID,
				TAKIM_STATUSU = ISK.TAKIM_STATUSU,
				DURAN_VARLIK = ISK.DURAN_VARLIK,
				KAP_KULLANIM_SEKLI = ISK.KAP_KULLANIM_SEKLI,
				SOZLESME_SATIR_TURU = ISK.SOZLESME_SATIR_TURU,
				DEPOMUZ_ID = ISK.DEPOMUZ_ID,
				REZERVE_EDILEN_MIKTAR = ISK.REZERVE_EDILEN_MIKTAR,
				BUTCE_TUTARI = ISK.BUTCE_TUTARI,
				GERCEKLESEN_MALIYET = ISK.GERCEKLESEN_MALIYET,
				GERCEKLESEN_MALIYET_KURU = ISK.GERCEKLESEN_MALIYET_KURU,
				EKIPMAN_ID = ISK.EKIPMAN_ID,
				PURSANTAJ_ORANI = ISK.PURSANTAJ_ORANI,
				IHZARAT_ODEME_ORANI = ISK.IHZARAT_ODEME_ORANI,
				FIYAT_DEGISTI = ISK.FIYAT_DEGISTI,
				IMALAT_AKTIVITE_ORANI = ISK.IMALAT_AKTIVITE_ORANI,
				URUN_FATURA_ADI = ISK.URUN_FATURA_ADI,
				GELDIGI_YER_ID = ISK.GELDIGI_YER_ID,
				SOZLESME_SATIRI_ID = ISK.SOZLESME_SATIRI_ID,
				PALET_ID = ISK.PALET_ID,
				PALET_MIKTARI = ISK.PALET_MIKTARI,
				AMBALAJ_RECETESI_ID = ISK.AMBALAJ_RECETESI_ID,
				PALET_RECETESI_ID = ISK.PALET_RECETESI_ID,
				KAR_ORANI = ISK.KAR_ORANI,
				DURAN_VARLIK_ID = ISK.ZIMMET_VARLIK_ID,
				PERSONEL_ID = ISK.PERSONEL_ID,
				PAKET_SAYISI = ISK.PAKET_SAYISI,
				PAKET_FIYATI = ISK.PAKET_FIYATI,
				BUTCE_ASIMI = ISK.BUTCE_ASIMI
		FROM TOHOM_SIPARIS_SATIRI S
			INNER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON S.SIPARIS_SATIRI_ID = ISK.SATIR_ID
		WHERE ISK.GUID = @GUID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60214
			GOTO UNDO
		END
		UPDATE S SET ODEME_BASLANGICI = ISK.ODEME_BASLANGICI,
				SATIR_NO = ISK.SATIR_NO,
				GUN_SAYISI = ISK.GUN_SAYISI,
				TARIH = ISK.TARIH,
				ORAN = ISK.ORAN,
				MIKTAR = ISK.MIKTAR,
				ODEME_SEKLI = ISK.ODEME_SEKLI,
				ACIKLAMA = ISK.ACIKLAMA,
				SATIR_TURU = ISK.SATIR_TURU,
				EVRAK_ORANI = ISK.EVRAK_ORANI,
				KESINTI_ID = ISK.KESINTI_ID
		FROM TOHOM_ODEME_PLANI_SATIRI S
			INNER JOIN TOHOM_ISKELE_ODEME_PLANI_SATIRI ISK ON S.ODEME_PLANI_SATIRI_ID = ISK.ODEME_PLANI_SATIRI_ID
		WHERE ISK.GUID = @GUID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60060
			GOTO UNDO
		END
	END
	/* iskelede olup da veritabanında olmayanları ekleyelim*/
	INSERT INTO TOHOM_SIPARIS_SATIRI
		(SIPARIS_ID,
			SATIR_NO,
			SATIR_TURU,
			KALEM_NO,
			URUN_YAMASI_ID,
			DARA,
			DARA_BIRIMI_ID,
			MIKTAR,
			BIRIM_ID,
			ALAN,
			ALAN_BIRIM_FIYATI,
			KIRA_CIRO_ORANI,
			BIRIM_FIYATI,
			PARA_ID,
			NAKLIYE_MALZEME_FIYATI,
			NAKLIYE_MALZEME_PARA_ID,
			KUR,
			TUTAR_HESAPLANMASIN,
			TUTAR,
			KDVSIZ_TUTAR,
			ISKONTO_ORANI,
			ISKONTO_HESAPLANMASIN,
			ISKONTO,
			ISKONTO_PAYI,
			RUSUM_ORANI,
			RUSUM_HESAPLANMASIN,
			RUSUM,
			BEYAN_EDILECEK_OTV,
			KDV_FIYATA_DAHIL,
			KDV_ORANI,
			ONCEKI_ID,
			TEKLIF_SATIRI_ID,
			IPTAL_SATIRI_ID,
			KAPANDI,
			FIYAT2,
			PARA2_ID,
			KUR2,
			TUTAR2,
			FIYAT3,
			PARA3_ID,
			KUR3,
			TUTAR3,
			GENEL_GIDER_PAYI,
			GENEL_GIDER_PAYI_PARA_ID,
			GENEL_GIDER_KURU,
			KAR_PAYI,
			KAR_PAYI_PARA_ID,
			KAR_KURU,
			PROJEMIZ_ID,
			AKTIVITE_ID,
			MASRAF_MERKEZI_ID,
			BUTCE_KALEMI_ID,
			BUTCE_BOLUMU_ID,
			LISTE_FIYATI,
			LISTE_FIYATI_PARA_ID,
			TAKIM_STATUSU,
			DURAN_VARLIK,
			KAP_KULLANIM_SEKLI,
			SOZLESME_SATIR_TURU,
			DEPOMUZ_ID,
			REZERVE_EDILEN_MIKTAR,
			BUTCE_TUTARI,
			GERCEKLESEN_MALIYET,
			GERCEKLESEN_MALIYET_KURU,
			EKIPMAN_ID,
			PURSANTAJ_ORANI,
			IHZARAT_ODEME_ORANI,
			FIYAT_DEGISTI,
			IMALAT_AKTIVITE_ORANI,
			URUN_FATURA_ADI,
			GELDIGI_YER_ID,
			SOZLESME_SATIRI_ID,
			PALET_ID,
			PALET_MIKTARI,
			AMBALAJ_RECETESI_ID,
			PALET_RECETESI_ID,
			KAR_ORANI,
			DURAN_VARLIK_ID,
			PERSONEL_ID,
			PAKET_SAYISI,
			PAKET_FIYATI,
			BUTCE_ASIMI)
	SELECT  @SIPARIS_ID,
			SATIR_NO,
			SATIR_TURU,
			KALEM_NO,
			URUN_YAMASI_ID,
			DARA,
			DARA_BIRIMI_ID,
			MIKTAR,
			BIRIM_ID,
			ALAN,
			ALAN_BIRIM_FIYATI,
			KIRA_CIRO_ORANI,
			BIRIM_FIYATI,
			PARA_ID,
			NAKLIYE_MALZEME_FIYATI,
			NAKLIYE_MALZEME_PARA_ID,
			KUR,
			TUTAR_HESAPLANMASIN,
			TUTAR,
			KDVSIZ_TUTAR,
			ISKONTO_ORANI,
			ISKONTO_HESAPLANMASIN,
			ISKONTO,
			ISKONTO_PAYI,
			RUSUM_ORANI,
			RUSUM_HESAPLANMASIN,
			CASE WHEN @OTV_VAR = 1 THEN RUSUM ELSE 0.0 END,
			RUSUM,
			KDV_FIYATA_DAHIL,
			KDV_ORANI,
			ONCEKI_ID,
			XID_1,
			CASE WHEN @IPTAL_FISI = 1 THEN XID_2 ELSE NULL END,
			KAPANDI,
			FIYAT2,
			PARA2_ID,
			KUR2,
			TUTAR2,
			FIYAT3,
			PARA3_ID,
			KUR3,
			TUTAR3,
			GENEL_GIDER_PAYI,
			GENEL_GIDER_PAYI_PARA_ID,
			GENEL_GIDER_KURU,
			KAR_PAYI,
			KAR_PAYI_PARA_ID,
			KAR_KURU,
			PROJEMIZ_ID,
			AKTIVITE_ID,
			MASRAF_MERKEZI_ID,
			BUTCE_KALEMI_ID,
			BUTCE_BOLUMU_ID,
			LISTE_FIYATI,
			LISTE_FIYATI_PARA_ID,
			TAKIM_STATUSU,
			DURAN_VARLIK,
			KAP_KULLANIM_SEKLI,
			SOZLESME_SATIR_TURU,
			DEPOMUZ_ID,
			REZERVE_EDILEN_MIKTAR,
			BUTCE_TUTARI,
			GERCEKLESEN_MALIYET,
			GERCEKLESEN_MALIYET_KURU,
			EKIPMAN_ID,
			PURSANTAJ_ORANI,
			IHZARAT_ODEME_ORANI,
			FIYAT_DEGISTI,
			IMALAT_AKTIVITE_ORANI,
			URUN_FATURA_ADI,
			GELDIGI_YER_ID,
			SOZLESME_SATIRI_ID,
			PALET_ID,
			PALET_MIKTARI,
			AMBALAJ_RECETESI_ID,
			PALET_RECETESI_ID,
			KAR_ORANI,
			ZIMMET_VARLIK_ID,
			PERSONEL_ID,
			PAKET_SAYISI,
			PAKET_FIYATI,
			BUTCE_ASIMI
	FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI
	WHERE SATIR_ID IS NULL AND GUID = @GUID
	ORDER BY KALEM_NO
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60126
		GOTO UNDO
	END
	UPDATE SS
		SET ONCEKI_MIKTAR = SS.MIKTAR
		FROM TOHOM_SIPARIS_SATIRI SS
			INNER JOIN TOHOM_SIPARIS S ON S.SIPARIS_ID = SS.SIPARIS_ID
			INNER JOIN TOHOM_EVRAK_KONUSU EK ON EK.EVRAK_KONUSU_ID = S.EVRAK_KONUSU_ID
			INNER JOIN TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK ON ISK.SATIR_ID = SS.SIPARIS_SATIRI_ID
		WHERE ISK.GUID = @GUID AND EK.TEKLIFLERI_VAR = 1
	IF @TIP = 0 AND @IPTAL_FISI = 0 AND @SIPARIS_ALT_TUR = 1
	BEGIN
		UPDATE IE SET SIPARIS_SATIRI_ID = SS.SIPARIS_SATIRI_ID, TESLIMAT_DEPOSU_ID = DY.PARTI_YAMASI_ID
			FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI ISK
				INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SATIR_NO = ISK.SATIR_NO
				INNER JOIN TOHOM_IS_EMRI IE ON IE.IS_EMRI_ID = ISK.XID_2
				INNER JOIN TOHOM_PARTI_YAMASI SY ON SY.PARTI_YAMASI_ID = IE.SORUMLU_ID
				INNER JOIN TOHOM_PARTI_YAMASI DY ON DY.PARTI_ID = SY.PARTI_ID AND DY.TUR = 12
			WHERE ISK.GUID = @GUID AND SS.SIPARIS_ID = @SIPARIS_ID
	END
	/*tekliflerin kayıdı*/
	IF @TIP = 2
	BEGIN
		DECLARE @TEKLIF_ID KAYIT_ID
		DECLARE @URUN_YAMA_TURU TUR
		SELECT @TEKLIF_ID = TEKLIF_ID, @URUN_YAMA_TURU = CASE TIP WHEN 0 THEN 6 ELSE 8 END
		FROM TOHOM_TEKLIF WHERE ILGILI_ID = @SIPARIS_ID
/*		DELETE TOHOM_TEKLIF_SATIRI WHERE TEKLIF_ID = @TEKLIF_ID*/
		IF @TEKLIF_ID IS NOT NULL
		BEGIN
			INSERT INTO TOHOM_TEKLIF_SATIRI (
			       TEKLIF_ID,
			       SATIR_NO ,
			       SATIR_TURU,
			       URUN_YAMASI_ID,
			       MIKTAR,
			       BIRIM_ID,
			       BIRIM_FIYATI,
			       PARA_ID,
			       KUR,
			       TUTAR,
			       KDVSIZ_TUTAR,
			       ISKONTO_ORANI,
			       ISKONTO_HESAPLANMASIN,
			       ISKONTO,
			       ISKONTO_PAYI,
			       RUSUM_ORANI,
				   RUSUM_HESAPLANMASIN,
				   RUSUM,
			       KDV_FIYATA_DAHIL,
			       KDV_ORANI,
			       KALEM_NO,
			       MASRAF_MERKEZI_ID,
				   BUTCE_KALEMI_ID,
				   BUTCE_BOLUMU_ID,
			       PROJEMIZ_ID,
			       LISTE_FIYATI,
			       LISTE_FIYATI_PARA_ID,
			       TAKIM_STATUSU,
			       DURAN_VARLIK,
			       AKTIVITE_ID,
			       DARA,
			       DARA_BIRIMI_ID,
			       KAP_KULLANIM_SEKLI,
				   TALEP_SATIRI_ID)
			SELECT T.TEKLIF_ID,
			       S.SATIR_NO ,
			       S.SATIR_TURU,
			       UY1.PARTI_YAMASI_ID, /*S.URUN_YAMASI_ID,*/
			       S.MIKTAR,
			       S.BIRIM_ID,
			       S.BIRIM_FIYATI,
			       S.PARA_ID,
			       S.KUR,
			       S.TUTAR,
			       S.KDVSIZ_TUTAR,
			       S.ISKONTO_ORANI,
			       S.ISKONTO_HESAPLANMASIN,
			       S.ISKONTO,
			       S.ISKONTO_PAYI,
			       S.RUSUM_ORANI,
				   S.RUSUM_HESAPLANMASIN,
				   S.RUSUM,
			       S.KDV_FIYATA_DAHIL,
			       S.KDV_ORANI,
			       S.KALEM_NO,
			       S.MASRAF_MERKEZI_ID,
				   S.BUTCE_KALEMI_ID,
				   S.BUTCE_BOLUMU_ID,
			       S.PROJEMIZ_ID,
			       S.LISTE_FIYATI,
			       S.LISTE_FIYATI_PARA_ID,
			       S.TAKIM_STATUSU,
			       S.DURAN_VARLIK,
			       S.AKTIVITE_ID,
			       S.DARA,
			       S.DARA_BIRIMI_ID,
			       S.KAP_KULLANIM_SEKLI,
				SS.SIPARIS_SATIRI_ID
			FROM TOHOM_ISKELE_ALIM_SATIM_SATIRI S
				INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.KALEM_NO = S.KALEM_NO
				INNER JOIN TOHOM_PARTI_YAMASI UY ON S.URUN_YAMASI_ID = UY.PARTI_YAMASI_ID
				INNER JOIN TOHOM_PARTI_YAMASI UY1 ON UY.PARTI_ID = UY1.PARTI_ID AND UY1.TUR = @URUN_YAMA_TURU
				, TOHOM_TEKLIF T
			WHERE S.GUID = @GUID AND S.SATIR_ID IS NULL AND SS.SIPARIS_ID = @SIPARIS_ID AND T.ILGILI_ID = @SIPARIS_ID
			IF @@ERROR<>0
			BEGIN
				SET @HATA_NO = 60126
				GOTO UNDO
			END
		END
	END
	/*Detayları kaydedelim*/
	INSERT INTO TOHOM_EVRAK_DETAYI (EVRAK_TURU,
					EVRAK_ID,
					ODEME_PLANI_ID,
					ORTALAMA_VADE,
					ORTALAMA_VADE_BIRIMI,
					VALOR_ZAMANI,
					VALOR_ZAMAN_BIRIMI,
					VADE_FARKI_ORANI,
					VADE_FARKI_ZAMAN_BIRIMI,
					MUHATAP_BANKA_ID,
					FIRMAMIZ_BANKA_HESAP_ID,
					ODEME_YETKILISI_ID,
					ODEME_ADRESI,
					TICARET_SEKLI,
					TESLIMAT_YETKILISI_ID,
					TESLIMAT_ADRESI_ID,
					TESLIMAT_ADRESI,
					TESLIMAT_BICIMI,
					TESLIMAT_SEKLI_ID,
					TESLIMAT_SURESI,
					TESLIMAT_SURESI_BIRIMI,
					YOLA_CIKIS_TARIHI,
					YUKLEME_YERI,
					YUKLEME_TARIHI,
					VARACAGI_YER,
					TAHMINI_VARIS_TARIHI,
					NAKLIYATCI_ID,
					NAKLIYATCI_ACENTA_ID,
					NAKLIYAT_SIGORTASINI_USTLENEN,
					NAKLIYAT_SIGORTACISI_ID,
					NAKLIYAT_SIGORTACISI_ACENTA_ID,
					GUMRUKCU_ID,
					ULASIM_SEKLI_ID,
					ULASIM_DETAYI,
					KOMISYONCU_ID,
					KOMISYON_ORANI,
					FATURA_YETKILISI_ID,
					FATURA_ADRESI,
					HAKKINDA,
					NOT1,
					NOT2,
					NOT3,
					KEFIL_ID,
					KDV_TEVKIFAT_TANIMI_ID,
					NIHAI_MUSTERI_ID,
					GARANTI_SURESI,
					GARANTI_SURESI_BIRIMI,
					GARANTI_VEREN_ID,
					NAKLIYE_UCRETI_DAHIL,
					NAKLIYE_UCRETI,
					NAKLIYE_UCRETI_PARA_ID)
			VALUES (	2,
					@SIPARIS_ID,
					@ODEME_PLANI_ID,
					@ORTALAMA_VADE,
					@ORTALAMA_VADE_BIRIMI,
					@VALOR_ZAMANI,
					@VALOR_ZAMAN_BIRIMI,
					@VADE_FARKI_ORANI,
					@VADE_FARKI_ZAMAN_BIRIMI,
					@MUHATAP_BANKA_ID,
					@FIRMAMIZ_BANKA_HESAP_ID,
					@ODEME_YETKILISI_ID,
					@ODEME_ADRESI,
					@TICARET_SEKLI,
					@TESLIMAT_YETKILISI_ID,
					@TESLIMAT_ADRESI_ID,
					@TESLIMAT_ADRESI,
					@TESLIMAT_BICIMI,
					@TESLIMAT_SEKLI_ID,
					@TESLIMAT_SURESI,
					@TESLIMAT_SURESI_BIRIMI,
					@YOLA_CIKIS_TARIHI,
					@YUKLEME_YERI,
					@YUKLEME_TARIHI,
					@VARACAGI_YER,
					@TAHMINI_VARIS_TARIHI,
					@NAKLIYATCI_ID,
					@NAKLIYATCI_ACENTA_ID,
					@NAKLIYAT_SIGORTASINI_USTLENEN,
					@NAKLIYAT_SIGORTACISI_ID,
					@NAKLIYAT_SIGORTACISI_ACENTA_ID,
					@GUMRUKCU_ID,
					@ULASIM_SEKLI_ID,
					@ULASIM_DETAYI,
					@KOMISYONCU_ID,
					@KOMISYON_ORANI,
					@FATURA_YETKILISI_ID,
					@FATURA_ADRESI,
					@HAKKINDA,
					@NOT1,
					@NOT2,
					@NOT3,
					@KEFIL_ID,
					@KDV_TEVKIFAT_TANIMI_ID,
					@NIHAI_MUSTERI_ID,
					@GARANTI_SURESI,
					@GARANTI_SURESI_BIRIMI,
					@GARANTI_VEREN_ID,
					@NAKLIYE_UCRETI_DAHIL,
					@NAKLIYE_UCRETI,
					@NAKLIYE_UCRETI_PARA_ID)
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60125
		GOTO UNDO
	END
	INSERT INTO TOHOM_EVRAK_DETAYI
		(	EVRAK_TURU,
			EVRAK_ID,
			ODEME_PLANI_ID,
			ORTALAMA_VADE,
			ORTALAMA_VADE_BIRIMI,
			VALOR_ZAMANI,
			VALOR_ZAMAN_BIRIMI,
			VADE_FARKI_ORANI,
			VADE_FARKI_ZAMAN_BIRIMI,
			MUHATAP_BANKA_ID,
			FIRMAMIZ_BANKA_HESAP_ID,
			ODEME_YETKILISI_ID,
			ODEME_ADRESI,
			TESLIMAT_YETKILISI_ID,
			TESLIMAT_ADRESI_ID,
			TESLIMAT_ADRESI,
			TESLIMAT_BICIMI,
			TESLIMAT_SEKLI_ID,
			TESLIMAT_SURESI,
			TESLIMAT_SURESI_BIRIMI,
			YOLA_CIKIS_TARIHI,
			YUKLEME_YERI,
			YUKLEME_TARIHI,
			VARACAGI_YER,
			TAHMINI_VARIS_TARIHI,
			NAKLIYATCI_ID,
			NAKLIYATCI_ACENTA_ID,
			NAKLIYAT_SIGORTASINI_USTLENEN,
			NAKLIYAT_SIGORTACISI_ID,
			NAKLIYAT_SIGORTACISI_ACENTA_ID,
			GUMRUKCU_ID,
			ULASIM_SEKLI_ID,
			ULASIM_DETAYI,
			KOMISYONCU_ID,
			KOMISYON_ORANI,
			FATURA_YETKILISI_ID,
			FATURA_ADRESI,
			HAKKINDA,
			NOT1,
			NOT2,
			NOT3,
			KDV_TEVKIFAT_TANIMI_ID,
			NAKLIYE_UCRETI_DAHIL,
			NAKLIYE_UCRETI,
			NAKLIYE_UCRETI_PARA_ID)
	SELECT  	3,
			S.SIPARIS_SATIRI_ID,
			D.ODEME_PLANI_ID,
			D.ORTALAMA_VADE,
			D.ORTALAMA_VADE_BIRIMI,
			D.VALOR_ZAMANI,
			D.VALOR_ZAMAN_BIRIMI,
			D.VADE_FARKI_ORANI,
			D.VADE_FARKI_ZAMAN_BIRIMI,
			D.MUHATAP_BANKA_ID,
			D.FIRMAMIZ_BANKA_HESAP_ID,
			D.ODEME_YETKILISI_ID,
			D.ODEME_ADRESI,
			D.TESLIMAT_YETKILISI_ID,
			D.TESLIMAT_ADRESI_ID,
			D.TESLIMAT_ADRESI,
			D.TESLIMAT_BICIMI,
			D.TESLIMAT_SEKLI_ID,
			D.TESLIMAT_SURESI,
			D.TESLIMAT_SURESI_BIRIMI,
			D.YOLA_CIKIS_TARIHI,
			D.YUKLEME_YERI,
			D.YUKLEME_TARIHI,
			D.VARACAGI_YER,
			D.TAHMINI_VARIS_TARIHI,
			D.NAKLIYATCI_ID,
			D.NAKLIYATCI_ACENTA_ID,
			D.NAKLIYAT_SIGORTASINI_USTLENEN,
			D.NAKLIYAT_SIGORTACISI_ID,
			D.NAKLIYAT_SIGORTACISI_ACENTA_ID,
			D.GUMRUKCU_ID,
			D.ULASIM_SEKLI_ID,
			D.ULASIM_DETAYI,
			D.KOMISYONCU_ID,
			D.KOMISYON_ORANI,
			D.FATURA_YETKILISI_ID,
			D.FATURA_ADRESI,
			D.HAKKINDA,
			D.NOT1,
			D.NOT2,
			D.NOT3,
			D.KDV_TEVKIFAT_TANIMI_ID,
			D.NAKLIYE_UCRETI_DAHIL,
			D.NAKLIYE_UCRETI,
			D.NAKLIYE_UCRETI_PARA_ID
	FROM TOHOM_ISKELE_EVRAK_DETAYI D INNER JOIN TOHOM_SIPARIS_SATIRI S ON  D.SATIR_NO = S.SATIR_NO AND S.SATIR_TURU = 0
	WHERE S.SIPARIS_ID = @SIPARIS_ID AND D.GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60127
		GOTO UNDO
	END
	INSERT INTO TOHOM_EVRAK_VERGISI
			(EVRAK_TURU,
			EVRAK_ID,
			TUR,
			ALT_TUR,
			ORAN,
			KDV_TEVKIFAT_TANIMI_ID,
			MATRAH,
			VERGI_HESAPLANSIN,
			KESINTI_PAYI,
			KESINTI_PAYDASI,
			KESILEN_VERGI,
			TAHSIL_EDILEN_VERGI)
		SELECT  2,
			@SIPARIS_ID,
			TUR,
			ALT_TUR,
			ORAN,
			KDV_TEVKIFAT_TANIMI_ID,
			MATRAH,
			VERGI_HESAPLANSIN,
			KESINTI_PAYI,
			KESINTI_PAYDASI,
			KESILEN_VERGI,
			TAHSIL_EDILEN_VERGI
			FROM TOHOM_ISKELE_EVRAK_VERGISI
		WHERE GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60103
		GOTO UNDO
	END
	INSERT INTO TOHOM_SIPARIS_URUN_FIYATI
			(SIPARIS_SATIRI_ID,
			BASLANGIC_TARIHI,
			BITIS_TARIHI,
			ALAN_BIRIM_FIYATI,
			FIYAT,
			PARA_ID,
			KUR,
			ACIKLAMA,
			ODEME_DONEMI)
		SELECT  S.SIPARIS_SATIRI_ID,
			ISK.BASLANGIC_TARIHI,
			ISK.BITIS_TARIHI,
			ISK.ALAN_BIRIM_FIYATI,
			ISK.FIYAT,
			ISK.PARA_ID,
			ISK.KUR,
			ISK.ACIKLAMA,
			ISK.ODEME_DONEMI
		FROM TOHOM_ISKELE_SIPARIS_URUN_FIYATI ISK
			INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SATIR_NO = ISK.FIS_SATIR_NO AND S.SATIR_TURU = 0
		WHERE S.SIPARIS_ID = @SIPARIS_ID AND ISK.GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60489
		GOTO UNDO
	END
	IF @TIP = 2
	BEGIN
		INSERT INTO TOHOM_TALEP_SIPARIS_BAGI
				(TALEP_SATIRI_ID,
				SIPARIS_SATIRI_ID,
				MIKTAR)
			SELECT S.SIPARIS_SATIRI_ID,
					ISK.SIPARIS_SATIRI_ID,
					ISK.MIKTAR
			FROM TOHOM_ISKELE_TESLIMAT_PLANI ISK
				INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SATIR_NO = ISK.FIS_SATIR_NO AND S.SATIR_TURU = 0
			WHERE ISK.GUID = @GUID AND S.SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60752
			GOTO UNDO
		END
	END
	ELSE BEGIN
		INSERT INTO TOHOM_TESLIMAT_PLANI
				(SAHIP_ID,
				SAHIP_TURU,
				SATIR_NO,
				TESLIMAT_TARIHI,
				MIKTAR,
				CEKI_NO,
				ACIKLAMA)
			SELECT  S.SIPARIS_SATIRI_ID,
					1,
					ISK.SATIR_NO,
					ISK.TESLIMAT_TARIHI,
					ISK.MIKTAR,
					ISK.CEKI_NO,
					ISK.ACIKLAMA
			FROM TOHOM_ISKELE_TESLIMAT_PLANI ISK
				INNER JOIN TOHOM_SIPARIS_SATIRI S ON S.SATIR_NO = ISK.FIS_SATIR_NO AND S.SATIR_TURU = 0
			WHERE ISK.GUID = @GUID AND S.SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60058
			GOTO UNDO
		END
	END
	INSERT INTO TOHOM_ODEME_PLANI_SATIRI
			(SAHIP_TURU,
			SAHIP_ID,
			ODEME_BASLANGICI,
			SATIR_NO,
			GUN_SAYISI,
			TARIH,
			EVRAK_ORANI,
			ORAN,
			MIKTAR,
			ODEME_SEKLI,
			ACIKLAMA,
			KESINTI_ID,
			SATIR_TURU)
		SELECT  23,
				@SIPARIS_ID,
				ODEME_BASLANGICI,
				SATIR_NO,
				GUN_SAYISI,
				TARIH,
				EVRAK_ORANI,
				ORAN,
				MIKTAR,
				ODEME_SEKLI,
				ACIKLAMA,
				KESINTI_ID,
				SATIR_TURU
			FROM TOHOM_ISKELE_ODEME_PLANI_SATIRI
			WHERE ODEME_PLANI_SATIRI_ID IS NULL AND GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60060
		GOTO UNDO
	END
	INSERT INTO TOHOM_KREDI_ODEME_PLANI
			(SAHIP_TURU,
			SAHIP_ID,
			SATIR_NO,
			TARIH,
			FAIZ_ORANI,
			ANAPARA,
			FAIZ,
			VERGI,
			YIL,
			AY)
		SELECT  0,
				@SIPARIS_ID,
				SATIR_NO,
				TARIH,
				FAIZ_ORANI,
				ANAPARA,
				FAIZ,
				VERGI,
				YIL,
				AY
			FROM TOHOM_ISKELE_KREDI_ODEME_PLANI
			WHERE GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60060
		GOTO UNDO
	END
	INSERT INTO TOHOM_SIPARIS_KESINTISI
		(SIPARIS_ID,
		KESINTI_ID,
		ORAN,
		FIYAT,
		PARA_ID,
		MASRAF_MERKEZI_ID,
		ACIKLAMA,
		SATIR_TURU,
		HESAPLAMA_SEKLI)
	SELECT
		@SIPARIS_ID,
		KESINTI_ID,
		ORAN,
		KESINTI,
		PARA_ID,
		MASRAF_MERKEZI_ID,
		ACIKLAMA,
		SATIR_TURU,
		HESAPLAMA_SEKLI
	FROM TOHOM_ISKELE_FATURA_KESINTISI
	WHERE GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60601
		GOTO UNDO
	END
	INSERT INTO TOHOM_EVRAK_TEMINATI
		(EVRAK_TURU,
		EVRAK_ID,
		SATIR_NO,
		TUR,
		MIKTAR,
		PARA_ID,
		TEMINAT_ARACI,
		TEMINAT_MEKTUBU_BITIS_TARIHI,
		EVRAKDA_YAZSIN,
		SATIR_TURU,
		ACIKLAMA)
	SELECT 2,
		@SIPARIS_ID,
		SATIR_NO,
		TUR,
		MIKTAR,
		PARA_ID,
		TEMINAT_ARACI,
		TEMINAT_MEKTUBU_BITIS_TARIHI,
		EVRAKDA_YAZSIN,
		SATIR_TURU,
		ACIKLAMA
	FROM TOHOM_ISKELE_EVRAK_TEMINATI
	WHERE GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60657
		GOTO UNDO
	END
	INSERT INTO TOHOM_SIPARIS_SORUMLUSU
		(SIPARIS_ID,
		SORUMLU_ID,
		SORUMLU_GOREVI,
		ACIKLAMA,
		ORAN)
	SELECT @SIPARIS_ID,
		SORUMLU_ID,
		SORUMLU_GOREVI,
		ACIKLAMA,
		ORAN
	FROM TOHOM_ISKELE_EVRAK_SORUMLUSU
	WHERE GUID = @GUID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60677
		GOTO UNDO
	END
	IF @TIP <> 1 OR @SENARYO <> 3 /*Konfeksiyon üretim satış siparişinde envanter ekranda satır detayında kaydediliyor*/
	BEGIN
		INSERT INTO TOHOM_ENVANTER_SATIRI_YATAY(SAHIP_TURU, SAHIP_ID, SATIR_NO, MIKTAR, ENVANTER0_ID, ENVANTER1_ID, ENVANTER2_ID, ENVANTER3_ID, ENVANTER4_ID)
			SELECT 2, S.SIPARIS_SATIRI_ID, ES.SATIR_NO, ES.MIKTAR, ES.ENVANTER0_ID, ES.ENVANTER1_ID, ES.ENVANTER2_ID, ES.ENVANTER3_ID, ES.ENVANTER4_ID
				FROM #TOHOM_ISKELE_ENVANTER_SATIRI_YATAY ES INNER JOIN TOHOM_SIPARIS_SATIRI S ON ES.FIS_SATIR_NO = S.SATIR_NO AND S.SATIR_TURU = 0
				WHERE S.SIPARIS_ID = @SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60415
			GOTO UNDO
		END
	END
	IF @KAYNAK_ID IS NOT NULL /* konfeksiyon satis siparisi cogaltma*/
	BEGIN
		INSERT INTO TOHOM_VARYANT_DEGERI(SIPARIS_SATIRI_ID, SATIR_NO, TABLO_MADDESI_ID, RENK_ID)
			SELECT S.SIPARIS_SATIRI_ID, D.SATIR_NO, D.TABLO_MADDESI_ID, D.RENK_ID
				FROM TOHOM_SIPARIS_SATIRI S
					INNER JOIN TOHOM_OLCU_BIRIMI OB ON OB.OLCU_BIRIMI_ID = S.BIRIM_ID
					INNER JOIN TOHOM_OLCU_SISTEMI OS ON OS.OLCU_SISTEMI_ID = OB.OLCU_SISTEMI_ID
					INNER JOIN TOHOM_SIPARIS_SATIRI PRV ON PRV.URUN_YAMASI_ID = S.URUN_YAMASI_ID
					INNER JOIN TOHOM_VARYANT_DEGERI D ON D.SIPARIS_SATIRI_ID = PRV.SIPARIS_SATIRI_ID
				WHERE S.SIPARIS_ID = @SIPARIS_ID AND PRV.SIPARIS_ID = @KAYNAK_ID AND ROUND(S.MIKTAR - PRV.MIKTAR, OS.MIKTAR_BASAMAK_SAYISI) = 0.0
		INSERT INTO TOHOM_ENVANTER_SATIRI_YATAY(SAHIP_TURU, SAHIP_ID, SATIR_NO, MIKTAR, ENVANTER0_ID, ENVANTER1_ID, ENVANTER2_ID, ENVANTER3_ID, ENVANTER4_ID)
			SELECT 2, S.SIPARIS_SATIRI_ID, ES.SATIR_NO, ES.MIKTAR, ES.ENVANTER0_ID, ES.ENVANTER1_ID, ES.ENVANTER2_ID, ES.ENVANTER3_ID, ES.ENVANTER4_ID
				FROM TOHOM_SIPARIS_SATIRI S
					INNER JOIN TOHOM_OLCU_BIRIMI OB ON OB.OLCU_BIRIMI_ID = S.BIRIM_ID
					INNER JOIN TOHOM_OLCU_SISTEMI OS ON OS.OLCU_SISTEMI_ID = OB.OLCU_SISTEMI_ID
					INNER JOIN TOHOM_SIPARIS_SATIRI PRV ON PRV.URUN_YAMASI_ID = S.URUN_YAMASI_ID
					INNER JOIN TOHOM_ENVANTER_SATIRI_YATAY ES ON ES.SAHIP_TURU = 2 AND ES.SAHIP_ID = PRV.SIPARIS_SATIRI_ID
				WHERE S.SIPARIS_ID = @SIPARIS_ID AND PRV.SIPARIS_ID = @KAYNAK_ID AND ROUND(S.MIKTAR - PRV.MIKTAR, OS.MIKTAR_BASAMAK_SAYISI) = 0.0
	END
	INSERT INTO TOHOM_OZELLIK_DEGERI(SAHIP_TURU, SAHIP_ID, OZELLIK_ID, TUR, STRING_DEGER, TARIH_DEGERI, NUMERIK_DEGER, XID)
		SELECT 3, S.SIPARIS_SATIRI_ID, O.OZELLIK_ID, O.TUR, O.STRING_DEGER, O.TARIH_DEGERI, O.NUMERIK_DEGER, O.XID
			FROM #TOHOM_ISKELE_OZELLIK_DEGERI O INNER JOIN TOHOM_SIPARIS_SATIRI S ON O.SAHIP = S.SATIR_NO AND S.SATIR_TURU = 0
			WHERE S.SIPARIS_ID = @SIPARIS_ID
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60339
		GOTO UNDO
	END
	INSERT INTO TOHOM_OZELLIK_DEGERI(SAHIP_TURU, SAHIP_ID, OZELLIK_ID, TUR, STRING_DEGER, TARIH_DEGERI, NUMERIK_DEGER, XID, ACIKLAMA)
		SELECT 10, @SIPARIS_ID, O.OZELLIK_ID, O.TUR, O.STRING_DEGER, O.TARIH_DEGERI, O.NUMERIK_DEGER, O.XID, O.ACIKLAMA
			FROM #TOHOM_ISKELE_OZELLIK_DEGERI O
			WHERE O.SAHIP = -1 AND O.TUR = 4
	IF @@ERROR<>0
	BEGIN
		SET @HATA_NO = 60339
		GOTO UNDO
	END
	IF @YENI_KAYIT = 1 AND @KAYNAK_SIPARIS_ID IS NOT NULL
	BEGIN
		INSERT INTO TOHOM_SIPARIS_EKI(
			SIPARIS_ID,
			TUR,
			SATIR_NO,
			PARTI_YAMASI_ID,
			MIKTAR,
			BIRIM_ID,
			GOREV_ID,
			KADRO_SAYISI,
			ACIKLAMA,
			BIRIM_FIYATI,
			PARA_ID)
		SELECT
			@SIPARIS_ID,
			TUR,
			SATIR_NO,
			PARTI_YAMASI_ID,
			MIKTAR,
			BIRIM_ID,
			GOREV_ID,
			KADRO_SAYISI,
			ACIKLAMA,
			BIRIM_FIYATI,
			PARA_ID
		FROM TOHOM_SIPARIS_EKI
		WHERE SIPARIS_ID = @KAYNAK_SIPARIS_ID
		IF @@ERROR<>0
		BEGIN
			SET @HATA_NO = 60124
			GOTO UNDO
		END
		IF @TIP = 1 AND @SENARYO = 3
			INSERT INTO TOHOM_SIPARIS_SATIR_VARYANTI(SIPARIS_SATIRI_ID, SATIR_NO, TABLO_MADDESI_ID, ENVANTER_MADDESI_ID)
				SELECT SS.SIPARIS_SATIRI_ID, V.SATIR_NO, V.TABLO_MADDESI_ID, V.ENVANTER_MADDESI_ID
					FROM TOHOM_SIPARIS_SATIRI SS
						INNER JOIN TOHOM_SIPARIS_SATIRI KS ON KS.URUN_YAMASI_ID = SS.URUN_YAMASI_ID AND KS.SATIR_NO = SS.SATIR_NO
						INNER JOIN TOHOM_SIPARIS_SATIR_VARYANTI V ON V.SIPARIS_SATIRI_ID = KS.SIPARIS_SATIRI_ID
					WHERE SS.SIPARIS_ID = @SIPARIS_ID AND KS.SIPARIS_ID = @KAYNAK_SIPARIS_ID AND SS.SATIR_TURU = 0 AND KS.SATIR_TURU = 0
	END
	DECLARE @OTOMATIK_AVANS_TALEBI BOOL
	DECLARE @SOZLESME_AVAS_TALEBI_SECIMI TUR
	SELECT @OTOMATIK_AVANS_TALEBI = ISNULL(OTOMATIK_AVANS_TALEBI, 0), @SOZLESME_AVAS_TALEBI_SECIMI = ISNULL(SOZLESME_AVAS_TALEBI_SECIMI, 1) FROM TOHOM_TANIM
	DECLARE @OTOMATIK_AVANS_TALEBI_VAR BOOL
	SET @OTOMATIK_AVANS_TALEBI_VAR = 0
	IF @TIP = 0 AND @IPTAL_FISI = 0 AND @GERCEK_IS_NESNESI_ID <> 32 AND @OTOMATIK_AVANS_TALEBI = 1 SET @OTOMATIK_AVANS_TALEBI_VAR = 1
	IF ISNULL(@SAHIP_TURU,0) <> 1 AND EXISTS(SELECT * FROM TOHOM_AKTIVITE_FISI WHERE SIPARIS_ID = @SIPARIS_ID AND TIP = 1)
	BEGIN
		SELECT @HATA_MESAJI = CASE WHEN P.KOD IS NOT NULL THEN dbo.FOHOM_MESAJ_SOYLE(61992, RTRIM(P.KOD), RTRIM(PR.KOD), '')
									ELSE dbo.FOHOM_MESAJ_SOYLE(61993, RTRIM(PR.KOD), '', '')
								END + ' ' + dbo.FOHOM_MESAJ_SOYLE(61991, '', '', '')
			FROM
				(SELECT IE.PROJEMIZ_ID, F.PARA_ID
					FROM TOHOM_AKTIVITE_FISI F
						INNER JOIN TOHOM_IS_EMRI IE ON IE.IS_EMRI_ID = F.IS_EMRI_ID
					WHERE F.SIPARIS_ID = @SIPARIS_ID AND F.TIP = 1
					GROUP BY IE.PROJEMIZ_ID, F.PARA_ID
				) AS AX
				INNER JOIN TOHOM_PARA PR ON PR.PARA_ID = AX.PARA_ID
				LEFT OUTER JOIN TOHOM_PARTI_YAMASI PY ON PY.PARTI_YAMASI_ID = AX.PROJEMIZ_ID
				LEFT OUTER JOIN TOHOM_PARTI P ON P.PARTI_ID = PY.PARTI_ID
				LEFT OUTER JOIN
				(SELECT SS.PROJEMIZ_ID, CASE WHEN ISNULL(SP.FATURA_UYGULANAN_PARA_SECIMI, 1) = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END AS PARA_ID
					FROM TOHOM_SIPARIS SP
						INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_ID = SP.SIPARIS_ID
					WHERE SP.SIPARIS_ID = @SIPARIS_ID AND SS.SATIR_TURU = 0
					GROUP BY SS.PROJEMIZ_ID, CASE WHEN ISNULL(SP.FATURA_UYGULANAN_PARA_SECIMI, 1) = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END
				) AS SX ON ISNULL(SX.PROJEMIZ_ID, 0) = ISNULL(AX.PROJEMIZ_ID, 0) AND SX.PARA_ID = AX.PARA_ID
			WHERE SX.PARA_ID IS NULL
		IF @HATA_MESAJI IS NOT NULL GOTO UNDO
	END
	SET @FATURA_UYGULANAN_PARA_SECIMI = ISNULL(@FATURA_UYGULANAN_PARA_SECIMI,1)
	IF EXISTS(SELECT *
				FROM TOHOM_AVANS_TALEBI T
					INNER JOIN TOHOM_EVRAK_KONUSU EK ON EK.EVRAK_KONUSU_ID = T.EVRAK_KONUSU_ID
				WHERE EK.EVRAK_TURU = 14 AND T.ZEYILNAME_ID =  @SIPARIS_ID)
	BEGIN
		SELECT @HATA_MESAJI = CASE WHEN P.KOD IS NOT NULL THEN dbo.FOHOM_MESAJ_SOYLE(61994, RTRIM(P.KOD), RTRIM(PR.KOD), '')
									ELSE dbo.FOHOM_MESAJ_SOYLE(61995, RTRIM(PR.KOD), '', '')
								END + ' ' + dbo.FOHOM_MESAJ_SOYLE(61991, '', '', '')
			FROM
				(SELECT T.PROJEMIZ_ID, ISNULL(T.FARKLI_PARA_ID, T.PARA_ID) AS PARA_ID
					FROM TOHOM_AVANS_TALEBI T
						INNER JOIN TOHOM_EVRAK_KONUSU EK ON EK.EVRAK_KONUSU_ID = T.EVRAK_KONUSU_ID
					WHERE EK.EVRAK_TURU = 14 AND T.ZEYILNAME_ID =  @SIPARIS_ID
					GROUP BY T.PROJEMIZ_ID, ISNULL(T.FARKLI_PARA_ID, T.PARA_ID)
				) AS AX
				INNER JOIN TOHOM_PARA PR ON PR.PARA_ID = AX.PARA_ID
				LEFT OUTER JOIN TOHOM_PARTI_YAMASI PY ON PY.PARTI_YAMASI_ID = AX.PROJEMIZ_ID
				LEFT OUTER JOIN TOHOM_PARTI P ON P.PARTI_ID = PY.PARTI_ID
				LEFT OUTER JOIN
				(SELECT SS.PROJEMIZ_ID, CASE WHEN @FATURA_UYGULANAN_PARA_SECIMI = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END AS PARA_ID
					FROM TOHOM_SIPARIS SP
						INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_ID = SP.SIPARIS_ID
					WHERE SP.SIPARIS_ID = @SIPARIS_ID AND SS.SATIR_TURU = 0
					GROUP BY SS.PROJEMIZ_ID, CASE WHEN @FATURA_UYGULANAN_PARA_SECIMI = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END
				) AS SX ON ISNULL(SX.PROJEMIZ_ID, 0) = ISNULL(AX.PROJEMIZ_ID, 0) AND SX.PARA_ID = AX.PARA_ID
			WHERE SX.PARA_ID IS NULL
		IF @HATA_MESAJI IS NOT NULL GOTO UNDO
		IF @OTOMATIK_AVANS_TALEBI_VAR = 0 AND
			EXISTS(SELECT *
						FROM TOHOM_AVANS_TALEBI T
							INNER JOIN TOHOM_EVRAK_KONUSU EK ON EK.EVRAK_KONUSU_ID = T.EVRAK_KONUSU_ID
						WHERE T.TIP = 0 AND T.ZEYILNAME_ID = @SIPARIS_ID AND ISNULL(T.KAPANDI,0) = 0 AND T.IPTAL_TARIHI IS NULL AND EK.EVRAK_TURU = 14 AND ISNULL(EK.EKRAN_GIRIS_SENARYOSU, 0) = 0
				)
		BEGIN
			DECLARE @FIRMAMIZ_GUID GUID
			SELECT @FIRMAMIZ_GUID = Y.GUID FROM TOHOM_FIRMAMIZ F INNER JOIN TOHOM_PARTI_YAMASI Y ON Y.PARTI_YAMASI_ID = F.FIRMAMIZ_ID
			DECLARE @SUBE_GUID GUID
			IF ISNULL(@SATINALAN_SUBE_ID,1) <> 1 SELECT @SUBE_GUID = GUID FROM TOHOM_PARTI_YAMASI WHERE PARTI_YAMASI_ID = @SATINALAN_SUBE_ID
			ELSE IF ISNULL(@UYGULAYAN_SUBE_ID,1) <> 1 SELECT @SUBE_GUID = GUID FROM TOHOM_PARTI_YAMASI WHERE PARTI_YAMASI_ID = @UYGULAYAN_SUBE_ID
			DECLARE C_AVANS CURSOR STATIC LOCAL FOR
				SELECT SS.PROJEMIZ_ID, CASE WHEN @FATURA_UYGULANAN_PARA_SECIMI = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END
					FROM TOHOM_SIPARIS SP
						INNER JOIN TOHOM_SIPARIS_SATIRI SS ON SS.SIPARIS_ID = SP.SIPARIS_ID
					WHERE SP.SIPARIS_ID = @SIPARIS_ID AND SS.SATIR_TURU = 0
					GROUP BY SS.PROJEMIZ_ID, CASE WHEN @FATURA_UYGULANAN_PARA_SECIMI = 1 THEN SP.PARA_ID ELSE SS.PARA_ID END
			DECLARE @AVANS_PROJEMIZ_ID KAYIT_ID
			DECLARE @AVANS_PARA_ID KAYIT_ID
			DECLARE @TALEP_EDILEBILIR_AVANS_MIKTARI MIKTAR
			OPEN C_AVANS
			FETCH NEXT FROM C_AVANS INTO @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID
			WHILE @@FETCH_STATUS = 0
			BEGIN
				IF @ESKI_AVANS_YONETIMI_UYGULANSIN = 1
				BEGIN
					IF @SATINALAN_SUBE_ID IS NOT NULL AND @UYGULAYAN_SUBE_ID IS NOT NULL
					BEGIN
						IF @SATINALAN_SUBE_ID = @UYGULAYAN_SUBE_ID
						BEGIN
							IF @SATINALAN_SUBE_ID = 1
								EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE_ESKI @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, 0, @FIRMAMIZ_GUID, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
							ELSE
								EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE_ESKI @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, 1, @SUBE_GUID, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
						END
						ELSE BEGIN
							EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE_ESKI @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, 0, @FIRMAMIZ_GUID, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
							IF @TALEP_EDILEBILIR_AVANS_MIKTARI >= 0.0
								EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE_ESKI @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, 1, @SUBE_GUID, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
						END
					END
					ELSE EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE_ESKI @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, 0, @FIRMAMIZ_GUID, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
				END
				ELSE EXEC @DONUS_KODU = SOHOM_SIPARIS_TALEP_EDILEBILIR_AVANS_MIKTARINI_SOYLE @SIPARIS_ID, @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID, NULL, @TALEP_EDILEBILIR_AVANS_MIKTARI OUT
				IF @DONUS_KODU = 2
				BEGIN
					SET @HATA_NO = 61979
					BREAK
				END
				IF @TALEP_EDILEBILIR_AVANS_MIKTARI < 0.0
				BEGIN
					SELECT @HATA_MESAJI = CASE WHEN P.KOD IS NOT NULL THEN dbo.FOHOM_MESAJ_SOYLE(61996, RTRIM(P.KOD), RTRIM(PR.KOD), '')
												ELSE dbo.FOHOM_MESAJ_SOYLE(61997, RTRIM(PR.KOD), '', '')
											END + ' ' + dbo.FOHOM_MESAJ_SOYLE(61998, '', '', '')
						FROM TOHOM_PARTI_YAMASI PY
							INNER JOIN TOHOM_PARTI P ON P.PARTI_ID = PY.PARTI_ID,
							TOHOM_PARA PR
						WHERE PY.PARTI_YAMASI_ID = @AVANS_PROJEMIZ_ID AND PR.PARA_ID = @AVANS_PARA_ID
					BREAK
				END
			FETCH NEXT FROM C_AVANS INTO @AVANS_PROJEMIZ_ID, @AVANS_PARA_ID
			END
			CLOSE C_AVANS
			DEALLOCATE C_AVANS
			IF @HATA_MESAJI IS NOT NULL OR @HATA_NO IS NOT NULL GOTO UNDO
		END
	END
	IF @TIP = 0
	BEGIN
		SET ROWCOUNT 1
		SELECT @HATA_MESAJI = dbo.FOHOM_MESAJ_SOYLE (61054, LTRIM(STR(SS.SATIR_NO+1)), '', '')
			FROM TOHOM_SIPARIS_SATIRI SS
				INNER JOIN VOHOM_SOZLESME_BAGI_KALAN K ON K.SOZLESME_SATIRI_ID = SS.SIPARIS_SATIRI_ID
			WHERE SS.SIPARIS_ID = @SIPARIS_ID AND K.KALAN_MIKTAR < 0.0
		SET ROWCOUNT 0
		IF @HATA_MESAJI IS NOT NULL GOTO UNDO
	END
	IF @TIP = 0 AND @IPTAL_FISI = 1
	BEGIN
			EXEC @DONUS_KODU = SOHOM_IPTAL_SIPARISI_CARI_HAREKET_KAYDET @SIPARIS_ID, @TARIH, @SIPARIS_NO, @KULLANICI_ID, @ONAYLANDI, @HATA_NO OUT, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
	END
	ELSE IF @TIP = 1 AND @IPTAL_FISI = 0 AND (@SIPARIS_ALT_TUR = 8 OR EXISTS(SELECT * FROM TOHOM_SIPARIS S INNER JOIN TOHOM_AVANS_TALEBI AT ON AT.SIPARIS_ID = S.SIPARIS_ID WHERE S.SIPARIS_ID  = @SIPARIS_ID))
	BEGIN
		IF @SIPARIS_ALT_TUR <> 8
			INSERT INTO #TOHOM_ISKELE_CARI_HAREKET_SATIRI(CARI_ID, CARI_HESAP_TURU, PROJEMIZ_ID, VADE, TIP, ORAN, MIKTAR, PARA_ID, KUR, TUTAR, ODEME_SEKLI, ACIKLAMA, ODEME_EMRI_CARI_HAREKET_SATIRI_ID, KESINTI_ID, HESAP_ID, ODENDI, PARITE, KARSILIK, KARSILIK_PARA_ID)
				SELECT S.PARTI_YAMASI_ID, 1, SS.PROJEMIZ_ID, OS.TARIH, 0, ROUND((OS.MIKTAR*100)/TOS.TOPLAM_MIKTAR, PR.KURUS_BASAMAK_SAYISI), OS.MIKTAR, SS.PARA_ID, SS.KUR, (OS.MIKTAR*BIRIM_FIYATI*SS.KUR), OS.ODEME_SEKLI, OS.ACIKLAMA, NULL, NULL, NULL, 0, NULL, NULL, NULL
						FROM TOHOM_SIPARIS_SATIRI SS
							INNER JOIN TOHOM_SIPARIS S ON S.SIPARIS_ID = SS.SIPARIS_ID
							INNER JOIN TOHOM_ODEME_PLANI_SATIRI OS ON OS.SAHIP_ID = S.SIPARIS_ID AND OS.SAHIP_TURU = 23
							INNER JOIN (SELECT OS.SAHIP_ID, SUM(OS.MIKTAR) AS TOPLAM_MIKTAR
											FROM TOHOM_ODEME_PLANI_SATIRI OS
											WHERE OS.SAHIP_TURU = 23 AND OS.ODEME_BASLANGICI = 2
											GROUP BY OS.SAHIP_ID
										)TOS ON TOS.SAHIP_ID = S.SIPARIS_ID
							INNER JOIN TOHOM_PARA PR ON PR.PARA_ID = SS.PARA_ID
						WHERE SS.SIPARIS_ID = @SIPARIS_ID AND SS.KALEM_NO = 0 AND OS.ODEME_BASLANGICI = 2
		DECLARE @KAPORA MIKTAR
		DECLARE @KAPATAN_CARI_HAREKET_ID KAYIT_ID
		IF @TIP = 1 AND @SIPARIS_ALT_TUR = 8
		BEGIN
			DECLARE @TEKLIF_SATIRI_ID KAYIT_ID
			SET ROWCOUNT 1
			SELECT @TEKLIF_SATIRI_ID = TEKLIF_SATIRI_ID FROM TOHOM_SIPARIS_SATIRI WHERE SIPARIS_ID = @SIPARIS_ID AND TEKLIF_SATIRI_ID IS NOT NULL
			SET ROWCOUNT 0
			SELECT @KAPORA = SUM(CHS.MIKTAR), @KAPATAN_CARI_HAREKET_ID = CH.CARI_HAREKET_ID
				FROM TOHOM_TEKLIF_SATIRI S
					INNER JOIN TOHOM_TEKLIF T ON T.TEKLIF_ID = S.TEKLIF_ID
					INNER JOIN TOHOM_ODEME_BORDROSU OB ON OB.TEKLIF_ID = T.TEKLIF_ID
					INNER JOIN TOHOM_CARI_HAREKET CH ON CH.SAHIP_ID = OB.ODEME_BORDROSU_ID AND CH.SAHIP_TURU = 3
					INNER JOIN TOHOM_CARI_HAREKET_SATIRI CHS ON CHS.CARI_HAREKET_ID = CH.CARI_HAREKET_ID
			WHERE S.TEKLIF_SATIRI_ID = @TEKLIF_SATIRI_ID
			GROUP BY CH.CARI_HAREKET_ID
			IF @KAPATAN_CARI_HAREKET_ID IS NOT NULL
				DELETE FROM TOHOM_CARI_KAPAMA WHERE KAPATAN_CARI_HAREKET_ID = @KAPATAN_CARI_HAREKET_ID
		END
		EXEC @DONUS_KODU = SOHOM_CARI_HAREKET_KAYDET  23, @SIPARIS_ID,  @TARIH, @SIPARIS_NO, @TAKSITLENDIRME_SEKLI, @ODEME_PLANI_ID, @PESINAT, @TAKSIT_VADE_FARKI_ORANI,
							@TAKSIT_VADE_FARKI_ZAMAN_BIRIMI, @TAKSITLENDIRME_DEGISTIRILDI, 0, @ONAYLANDI, @KULLANICI_ID, NULL, @HATA_NO OUT, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
		IF @KAPATAN_CARI_HAREKET_ID IS NOT NULL
		BEGIN
			DECLARE @CARI_HAREKET_SATIRI_ID KAYIT_ID
			DECLARE @DUSULEN_KAPORA MIKTAR
			SET ROWCOUNT 1
			SELECT @CARI_HAREKET_SATIRI_ID = S.CARI_HAREKET_SATIRI_ID, @DUSULEN_KAPORA = S.MIKTAR
				FROM TOHOM_CARI_HAREKET H
					INNER JOIN TOHOM_CARI_HAREKET_SATIRI S ON S.CARI_HAREKET_ID = H.CARI_HAREKET_ID
				WHERE H.SAHIP_TURU = 23 AND H.SAHIP_ID = @SIPARIS_ID AND S.ODEME_SEKLI = 0
				ORDER BY S.VADE
			SET ROWCOUNT 0
			IF @CARI_HAREKET_SATIRI_ID IS NOT NULL
			BEGIN
				SELECT @KURUS_SAYISI = KURUS_BASAMAK_SAYISI FROM TOHOM_PARA WHERE PARA_ID = @PARA_ID
				IF ROUND(@DUSULEN_KAPORA, @KURUS_SAYISI) <> ROUND(@KAPORA, @KURUS_SAYISI)
				BEGIN
					SET @HATA_MESAJI = dbo.FOHOM_MESAJ_SOYLE (61056, LTRIM(STR(@KAPORA, 13, @KURUS_SAYISI)), '', '')
					GOTO UNDO
				END
				INSERT INTO TOHOM_CARI_KAPAMA(KAPATAN_CARI_HAREKET_ID, CARI_HAREKET_SATIRI_ID, MIKTAR)
					VALUES(@KAPATAN_CARI_HAREKET_ID, @CARI_HAREKET_SATIRI_ID, @KAPORA)
			END
		END
	END
	IF @DENETIM_ISLEMI IN (1,2)
	BEGIN
		DELETE #TOHOM_ISKELE_AD
		DECLARE @UNVAN TANIM_ADI
		SELECT @UNVAN = P.UNVAN FROM TOHOM_PARTI P INNER JOIN TOHOM_PARTI_YAMASI Y ON Y.PARTI_ID = P.PARTI_ID WHERE Y.PARTI_YAMASI_ID = @PARTI_YAMASI_ID
		INSERT INTO #TOHOM_ISKELE_AD (DIL, AD)
			SELECT PA.DIL, PA.AD
				FROM TOHOM_PARTI_YAMASI Y
					INNER JOIN TOHOM_AD PA ON PA.SAHIP_TURU = 10 AND PA.SAHIP_ID = Y.PARTI_ID
				WHERE Y.PARTI_YAMASI_ID = @PARTI_YAMASI_ID
		SET @HAKKINDA = RTRIM(@SIPARIS_NO)
		SET @HAKKINDA = LEFT(ISNULL(@HAKKINDA + ' ', '')  + @UNVAN + ISNULL(' ' + @ACIKLAMA,''), 200)
		IF EXISTS(SELECT * FROM TOHOM_EVRAK_KONUSU WHERE EVRAK_KONUSU_ID = @EVRAK_KONUSU_ID AND EVRAK_TURU = 2 AND TEKLIFLERI_VAR = 1)
		BEGIN
			EXEC SOHOM_TEKLIF_DEGERLENDIRMEDE_SIPARISI_GUNCELLE @SIPARIS_ID, @KULLANICI_ID, NULL
			SELECT @TOPLAM_TUTAR = TOPLAM_TUTAR FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
		END
		EXEC @DONUS_KODU = SOHOM_ONAYA_SUN @KULLANICI_ID, @GUID, @DENETIM_ISLEMI, @YENI_KAYIT, @SIPARIS_ID, @IS_NESNESI_ID, @PROJEMIZ_ID, @HAKKINDA,  @HATA_NO OUT, @HATA_MESAJI OUT, @UNVAN, @TARIH, @ACIKLAMA
		IF @DONUS_KODU = 1 GOTO UNDO
	END
	IF EXISTS(SELECT name FROM sysobjects WHERE type = 'P' and name = 'S_SiparisOzellikHesapla')
	BEGIN
		EXEC @DONUS_KODU = S_SiparisOzellikHesapla @SIPARIS_ID, @TIP, @EVRAK_KONUSU_ID, @IPTAL_FISI, @DOKUMANI_VAR, @SOZLESME_DOKUMANI_VAR, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
	END
	IF @HESAP_HAREKETI_URET = 1
	BEGIN
		SET @DONUS_KODU = 0
		DELETE FROM #TOHOM_ISKELE_CARI_HAREKET_SATIRI
		INSERT INTO #TOHOM_ISKELE_CARI_HAREKET_SATIRI(CARI_ID, CARI_HESAP_TURU, PROJEMIZ_ID, VADE, TIP, ORAN, MIKTAR, PARA_ID, KUR, TUTAR, ODEME_SEKLI)
			SELECT @PARTI_YAMASI_ID, 0, @PROJEMIZ_ID, OP.TARIH, 1, 0.0,
							SUM(ROUND(OP.ANAPARA + OP.FAIZ + OP.VERGI, PR.KURUS_BASAMAK_SAYISI)),
							@PARA_ID, @KUR,
							ROUND(SUM(ROUND(OP.ANAPARA + OP.FAIZ + OP.VERGI , PR.KURUS_BASAMAK_SAYISI)) * @KUR, TL.KURUS_BASAMAK_SAYISI),
							0
				FROM TOHOM_KREDI_ODEME_PLANI OP, TOHOM_PARA PR, TOHOM_PARA TL
				WHERE OP.SAHIP_TURU = 0 AND OP.SAHIP_ID = @SIPARIS_ID AND PR.PARA_ID = @PARA_ID AND TL.PARA_ID = 1
				GROUP BY OP.TARIH, TL.KURUS_BASAMAK_SAYISI
		EXEC @DONUS_KODU = SOHOM_CARI_HAREKET_KAYDET  23, @SIPARIS_ID,  @TARIH, @SIPARIS_NO, 0, @ODEME_PLANI_ID, 0.0, NULL, NULL, 0, 0, @ONAYLANDI,
																									@KULLANICI_ID, NULL, @HATA_NO OUT, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
		IF @ONAYLANDI = 1 EXEC @DONUS_KODU = SOHOM_SIPARIS_HAREKETI_KAYDET  @SIPARIS_ID, @KULLANICI_ID, @HATA_NO OUT
		ELSE IF @YENI_KAYIT = 0 EXEC @DONUS_KODU = SOHOM_EVRAK_HAREKETI_SIL @SIPARIS_ID, 23, @KULLANICI_ID, @HATA_NO OUT
		IF (@DONUS_KODU = 1) GOTO UNDO
	END
	ELSE IF @CARI_HAREKET_URET = 1
	BEGIN
		SET @DONUS_KODU = 0
		DELETE FROM #TOHOM_ISKELE_CARI_HAREKET_SATIRI
		INSERT INTO #TOHOM_ISKELE_CARI_HAREKET_SATIRI(CARI_ID, CARI_HESAP_TURU, PROJEMIZ_ID, VADE, TIP, ORAN, MIKTAR, PARA_ID, KUR, TUTAR, ODEME_SEKLI)
			SELECT @PARTI_YAMASI_ID, 0, @PROJEMIZ_ID, CASE WHEN OP.TARIH IS NOT NULL THEN OP.TARIH ELSE DATEADD(DAY, OP.GUN_SAYISI, @TARIH) END, 0, 0.0, OP.MIKTAR, @PARA_ID, @KUR, ROUND(OP.MIKTAR * @KUR, TL.KURUS_BASAMAK_SAYISI), 0
				FROM TOHOM_ODEME_PLANI_SATIRI OP, TOHOM_PARA PR, TOHOM_PARA TL
				WHERE OP.SAHIP_TURU = 23 AND OP.SAHIP_ID = @SIPARIS_ID AND OP.ODEME_BASLANGICI = 2 AND TL.PARA_ID = 1
		EXEC @DONUS_KODU = SOHOM_CARI_HAREKET_KAYDET  23, @SIPARIS_ID,  @TARIH, @SIPARIS_NO, 0, @ODEME_PLANI_ID, 0.0, NULL, NULL, 0, 0, @ONAYLANDI,
																									@KULLANICI_ID, NULL, @HATA_NO OUT, @HATA_MESAJI OUT
		IF @DONUS_KODU = 1 GOTO UNDO
	END
/*	SET @OTOMATIK_AVANS_TALEBI_VAR = 0*/
	IF @OTOMATIK_AVANS_TALEBI_VAR = 1
	BEGIN
		DECLARE @ZEYILNAME_NO TAMSAYI
		SELECT @ZEYILNAME_NO = ZEYILNAME_NO FROM TOHOM_SIPARIS WHERE SIPARIS_ID = @SIPARIS_ID
		IF @SOZLESME_AVAS_TALEBI_SECIMI = 1 OR ISNULL(@ZEYILNAME_NO, 0) = 0
		BEGIN
			IF @ESKI_AVANS_YONETIMI_UYGULANSIN = 1
			BEGIN
				EXEC SOHOMC_SIPARIS_AVANS_TALEBI_ESKI @SIPARIS_ID, @ZEYILNAME_NO
				EXEC @DONUS_KODU = SOHOM_SIPARIS_AVANS_TALEBI_KAYDET_ESKI 0, @SIPARIS_ID, @PARTI_YAMASI_ID, @TARIH, 2, @ONAYLANDI, @KULLANICI_ID, @GUID, @HATA_NO OUT, @HATA_MESAJI OUT
			END
			ELSE BEGIN
				EXEC SOHOMC_SIPARIS_AVANS_TALEBI @SIPARIS_ID, @ZEYILNAME_NO, 2, @TARIH, 1
				EXEC @DONUS_KODU = SOHOM_SIPARIS_AVANS_TALEBI_KAYDET @SIPARIS_ID, @PARTI_YAMASI_ID, @TARIH, @ONAYLANDI, @KULLANICI_ID, @GUID, @HATA_NO OUT, @HATA_MESAJI OUT
			END
			IF @DONUS_KODU = 1 GOTO UNDO
		END
	END
	IF EXISTS(SELECT *
				FROM TOHOM_SIPARIS_SATIRI SS
					INNER JOIN TOHOM_IS_EMRI IE ON SS.SIPARIS_SATIRI_ID = IE.SIPARIS_SATIRI_ID
				WHERE SS.SIPARIS_ID = @SIPARIS_ID AND SS.MIKTAR <> IE.PLANLANAN_MIKTAR)
	BEGIN
		UPDATE RS SET IHTIYAC =  CASE WHEN ISNULL(IE.PLANLANAN_MIKTAR,0.0) <> 0.0 THEN ROUND(SS.MIKTAR * RS.IHTIYAC / IE.PLANLANAN_MIKTAR, OS.MIKTAR_BASAMAK_SAYISI) ELSE RS.IHTIYAC END
			FROM TOHOM_SIPARIS_SATIRI SS
				INNER JOIN TOHOM_IS_EMRI IE ON SS.SIPARIS_SATIRI_ID = IE.SIPARIS_SATIRI_ID
				INNER JOIN TOHOM_RECETE_SATIRI RS ON IE.IS_EMRI_ID = RS.IS_EMRI_ID
				INNER JOIN TOHOM_OLCU_BIRIMI OB ON RS.BIRIM_ID = OB.OLCU_BIRIMI_ID
				INNER JOIN TOHOM_OLCU_SISTEMI OS ON OB.OLCU_SISTEMI_ID = OS.OLCU_SISTEMI_ID
			WHERE SS.SIPARIS_ID = @SIPARIS_ID AND IE.PLANLANAN_MIKTAR <> SS.MIKTAR
		DELETE ES
			FROM TOHOM_SIPARIS_SATIRI SS
				INNER JOIN TOHOM_IS_EMRI IE ON SS.SIPARIS_SATIRI_ID = IE.SIPARIS_SATIRI_ID
				INNER JOIN TOHOM_ENVANTER_SATIRI_YATAY ES ON ES.SAHIP_ID = IE.IS_EMRI_ID AND ES.SAHIP_TURU = 4
			WHERE SS.SIPARIS_ID = @SIPARIS_ID AND IE.PLANLANAN_MIKTAR <> SS.MIKTAR
		INSERT INTO TOHOM_ENVANTER_SATIRI_YATAY(SAHIP_TURU, SAHIP_ID, SATIR_NO, MIKTAR, ENVANTER0_ID, ENVANTER1_ID, ENVANTER2_ID, ENVANTER3_ID, ENVANTER4_ID, SAYIM_MIKTARI)
			SELECT 4, IE.IS_EMRI_ID, ES.SATIR_NO, ES.MIKTAR, ES.ENVANTER0_ID, ES.ENVANTER1_ID, ES.ENVANTER2_ID, ES.ENVANTER3_ID, ES.ENVANTER4_ID, ES.SAYIM_MIKTARI
				FROM TOHOM_SIPARIS_SATIRI SS
					INNER JOIN TOHOM_IS_EMRI IE ON SS.SIPARIS_SATIRI_ID = IE.SIPARIS_SATIRI_ID
					INNER JOIN TOHOM_ENVANTER_SATIRI_YATAY ES ON ES.SAHIP_ID = SS.SIPARIS_SATIRI_ID AND ES.SAHIP_TURU = 2
				WHERE SS.SIPARIS_ID = @SIPARIS_ID AND IE.PLANLANAN_MIKTAR <> SS.MIKTAR
		UPDATE IE SET IE.PLANLANAN_MIKTAR = SS.MIKTAR, IE.PLANLANAN_MIKTAR_BIRIM_ID = SS.BIRIM_ID
			FROM TOHOM_SIPARIS_SATIRI SS
				INNER JOIN TOHOM_IS_EMRI IE ON SS.SIPARIS_SATIRI_ID = IE.SIPARIS_SATIRI_ID
			WHERE SS.SIPARIS_ID = @SIPARIS_ID AND IE.PLANLANAN_MIKTAR <> SS.MIKTAR
	END
	DELETE TOHOM_ISKELE_ALIM_SATIM_SATIRI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_DETAYI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_VERGISI WHERE GUID = @GUID
	DELETE #TOHOM_ISKELE_ENVANTER_SATIRI_YATAY
	DELETE #TOHOM_ISKELE_OZELLIK_DEGERI
	DELETE TOHOM_ISKELE_SIPARIS_URUN_FIYATI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_TESLIMAT_PLANI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_KREDI_ODEME_PLANI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_FATURA_KESINTISI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_ODEME_PLANI_SATIRI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_TEMINATI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_XID WHERE GUID = @GUID
	RETURN 0
UNDO:
	DELETE TOHOM_ISKELE_ALIM_SATIM_SATIRI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_DETAYI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_VERGISI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_SIPARIS_URUN_FIYATI WHERE GUID = @GUID
	DELETE #TOHOM_ISKELE_ENVANTER_SATIRI_YATAY
	DELETE #TOHOM_ISKELE_OZELLIK_DEGERI
	DELETE TOHOM_ISKELE_SIPARIS_URUN_FIYATI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_TESLIMAT_PLANI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_KREDI_ODEME_PLANI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_FATURA_KESINTISI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_ODEME_PLANI_SATIRI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_EVRAK_TEMINATI WHERE GUID = @GUID
	DELETE TOHOM_ISKELE_XID WHERE GUID = @GUID
	IF @HATA_NO IS NOT NULL RAISERROR (@HATA_NO, 16, 1)
	ELSE IF @HATA_MESAJI IS NOT NULL RAISERROR (@HATA_MESAJI, 16, 1)
	RETURN 1
END
GO
